// scr_game_init.gml - Ported from Freeserf src/game-init.h / src/game-init.cc
// (GPL-3.0), original copyright (C) 2013-2018 Jon Lund Steffensen
// <jonlst@gmail.com>. Game initialization GUI component (the "new game" box)
// and the RandomInput text widget.
//
// freeserf is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Differences from the C++:
//  - There is no GameManager: ActionStartGame creates `new Game()`, runs
//    `mission.instantiate(game)` (scr_mission.gml) and hands the game to
//    `interface.on_new_game(game)`.
//  - Save/load (GameStore / GameManager::load_game) is not ported: the
//    GameLoad game type shows the (stub) ListSavedFiles but starting it does
//    nothing.
//  - RandomInput is a self-contained GuiObject here (it carries the parts of
//    TextInput it needs: text, max_length, filter, focus drawing, key input).
//    NOTE: scr_popup.gml currently contains a STUB `RandomInput` constructor
//    (lines ~2215-2228) that must be removed when this file is added.
//  - FREESERF_VERSION (generated by the build) is the GAME_INIT_VERSION macro.

#macro GAME_INIT_VERSION "SettlersGM"

// ---------------------------------------------------------------------------
// Version, and the update check behind the line at the bottom of the start
// screen.
//
// The running build's version is GM_version, which is the string set in Game
// Options for the target platform - so bumping the version is done in the IDE
// where it belongs, and nothing here has to be kept in step with it by hand.
//
// The latest available version is one line of text in the repository, fetched
// over HTTP at startup. A plain text file rather than JSON on purpose: there is
// nothing to parse, nothing to go wrong with a struct that turned out not to
// have the field, and it is one keystroke to edit. Only the FIRST line is read,
// so notes, a download URL or anything else can be added underneath later
// without breaking a build that is already out in the world.
// ---------------------------------------------------------------------------

#macro UPDATE_CHECK_URL "https://raw.githubusercontent.com/RobertRamsay/SettlersGM/main/version.txt"

/* Where the update note takes you when it is clicked: the itch page, which is
   where the builds are. A page rather than a direct download, because the file
   name changes with every version and the page does not. */
#macro UPDATE_PAGE_URL  "https://polytricity.itch.io/settlers-gm"

/* How fast the note flashes: the colour changes every this many milliseconds.
   Two colours rather than on and off, so it is never invisible at the moment
   somebody goes to click it. */
#macro UPDATE_FLASH_MS  400

/// The version this build reports, from Game Options.
function game_version() {
    return string(GM_version);
}

/// The version as the two platforms can agree on it: the first three numbers.
///
/// Windows Game Options hold four fields, macOS hold three, so the same
/// release reads "1.0.9.0" on one and "1.0.9" on the other. The fourth field
/// is never bumped - it is always the .0 - so it carries no information and
/// only ever made two matching builds look different. This is what the net
/// handshake compares and what it sends; the full string stays for the start
/// screen and the update check, which are each on one platform only.
function game_build_version() {
    var _v = game_version();
    var _out = "";
    var _fields = 0;
    var _n = string_length(_v);
    for (var _i = 1; _i <= _n; _i++) {
        var _c = string_char_at(_v, _i);
        if (_c == ".") {
            _fields += 1;
            if (_fields >= 3) {
                break;
            }
        }
        _out += _c;
    }
    return _out + "-speedfix1";
}

/// Everything the update check owns, laid out before anything can read it.
/// Called from obj_game Create.
function update_check_init() {
    global.update_request_id = -1;
    global.update_latest = "";
    global.update_available = false;
    global.update_checked = false;
}

/// Fire the request. Nothing waits on it: the answer turns up in obj_game's
/// Async HTTP event whenever it turns up, and if it never does - no network, a
/// proxy, GitHub having a bad day - the start screen simply never grows the
/// extra word. An update check is not allowed to be a reason the game does not
/// start.
function update_check_start() {
    update_check_init();
    global.update_request_id = http_get(UPDATE_CHECK_URL);
}

/// First line of a fetched file, without its line ending or surrounding space.
function update_first_line(_text) {
    var _s = string(_text);
    var _cut = string_length(_s);

    var _nl = string_pos("\n", _s);
    if (_nl > 0) {
        _cut = _nl - 1;
    }
    var _cr = string_pos("\r", _s);
    if (_cr > 0 && _cr - 1 < _cut) {
        _cut = _cr - 1;
    }

    return string_trim(string_copy(_s, 1, _cut));
}

/// Is this a version and nothing else? Digits and dots, at least one digit, and
/// short enough to be one. Anything else - a 404 page, a login redirect, an
/// error from a captive portal - is thrown away rather than displayed.
function update_looks_like_version(_str) {
    var _n = string_length(_str);
    if (_n < 1 || _n > 24) {
        return false;
    }

    /* string_pos against a set of characters rather than `_c >= "0"`: the
       relational operators are for numbers, and what GML does with them on two
       strings is not something worth finding out at a customer's machine. */
    var _digits = 0;
    for (var _i = 1; _i <= _n; _i++) {
        var _c = string_char_at(_str, _i);
        if (_c == ".") {
            continue;
        }
        if (string_pos(_c, "0123456789") == 0) {
            return false;
        }
        _digits += 1;
    }

    return (_digits > 0);
}

/// The _index'th dot-separated number of a version string, or 0 past the end.
/// Hand-rolled rather than string_split so that a version with any number of
/// parts compares against one with any other: "1.2" and "1.2.0.0" are equal.
function update_version_part(_str, _index) {
    var _from = 1;
    var _n = string_length(_str);
    var _part = 0;

    while (_part <= _index) {
        var _to = _from;
        while (_to <= _n && string_char_at(_str, _to) != ".") {
            _to += 1;
        }
        if (_part == _index) {
            if (_to == _from) {
                return 0;
            }
            return real(string_copy(_str, _from, _to - _from));
        }
        if (_to > _n) {
            return 0;
        }
        _from = _to + 1;
        _part += 1;
    }

    return 0;
}

/// Is _latest newer than _current? Compared number by number, never as strings,
/// because "1.0.10.0" sorts BEFORE "1.0.9.0" alphabetically and that would
/// announce an update that is really a downgrade.
function update_version_is_newer(_latest, _current) {
    for (var _i = 0; _i < 6; _i++) {
        var _l = update_version_part(_latest, _i);
        var _c = update_version_part(_current, _i);
        if (_l > _c) {
            return true;
        }
        if (_l < _c) {
            return false;
        }
    }

    return false;
}

/// obj_game's Async HTTP event hands the map straight here.
function update_check_handle_async(_async) {
    if (global.update_request_id < 0) {
        return;
    }
    if (_async[? "id"] != global.update_request_id) {
        return;
    }

    var _status = _async[? "status"];
    if (_status == 1) {
        /* Still downloading. */
        return;
    }

    global.update_request_id = -1;
    global.update_checked = true;

    if (_status != 0) {
        show_debug_message("update: check failed, status " + string(_status));
        return;
    }
    if (_async[? "http_status"] != 200) {
        show_debug_message("update: check got HTTP " + string(_async[? "http_status"]));
        return;
    }

    var _latest = update_first_line(_async[? "result"]);
    if (!update_looks_like_version(_latest)) {
        show_debug_message("update: ignoring unrecognised version file");
        return;
    }

    global.update_latest = _latest;
    global.update_available = update_version_is_newer(_latest, game_version());
    show_debug_message("update: running " + game_version() + ", latest " + _latest);
}

/// GameInitBox::Action
enum GameInitAction {
    start_game = 0,
    toggle_game_type,
    show_options,
    increment,
    decrement,
    close,
    gen_random,
    apply_random,
    show_load,
    show_netplay,
    netplay_add,
    netplay_host,
    open_update,
    toggle_language,
    netplay_mode_mission,
    netplay_mode_custom,
    netplay_new_map
}

/// GameInitBox::GameType
enum GameType {
    custom = 0,
    mission = 1,
    load = 2,
    netplay = 3
}

function game_init_init_tables() {
    if (variable_global_exists("game_init_layout")) {
        return;
    }

    global.game_init_color_green = make_colour_rgb(0x73, 0xb3, 0x43);
    global.game_init_color_black = make_colour_rgb(0x00, 0x00, 0x00);
    global.game_init_color_supplies = make_colour_rgb(0x00, 0x93, 0x87);
    global.game_init_color_intelligence = make_colour_rgb(0x6b, 0xab, 0x3b);
    global.game_init_color_reproduction = make_colour_rgb(0xa7, 0x27, 0x27);

    // TextInput colours
    global.game_init_color_focus = make_colour_rgb(0x00, 0x8b, 0x47);

    // internal_draw: const int layout[]
    global.game_init_layout = [
        266, 0, 0,    // Start button
        267, 36, 0,   // Options button
        -1
    ];

    // draw_player_box: const int layout[]
    global.game_init_player_layout = [
        251, 0, 0,
        252, 0, 72,
        253, 0, 8,
        254, 5, 8,
        255, 9, 8,
        -1
    ];

    // handle_click_left clickmaps
    global.game_init_clickmap_mission = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_load,        GAME_INIT_LOAD_X, GAME_INIT_LOAD_Y, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.increment,        284,  16, 16, 16,
        GameInitAction.decrement,        284,  32, 16, 16,
        GameInitAction.close,            GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, 16, 16,
        GameInitAction.open_update,      GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y, GAME_INIT_UPDATE_W, GAME_INIT_ROW_H,
        GameInitAction.toggle_language,  GAME_INIT_LANG_X, GAME_INIT_LANG_Y, GAME_INIT_LANG_W, GAME_INIT_ROW_H,
        -1
    ];

    global.game_init_clickmap_custom = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_load,        GAME_INIT_LOAD_X, GAME_INIT_LOAD_Y, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.increment,        220,  24, 24, 24,
        GameInitAction.decrement,        220,  16,  8,  8,
        GameInitAction.gen_random,       244,  16, 16,  8,
        GameInitAction.apply_random,     244,  24, 16, 24,
        GameInitAction.close,            GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, 16, 16,
        GameInitAction.open_update,      GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y, GAME_INIT_UPDATE_W, GAME_INIT_ROW_H,
        GameInitAction.toggle_language,  GAME_INIT_LANG_X, GAME_INIT_LANG_Y, GAME_INIT_LANG_W, GAME_INIT_ROW_H,
        -1
    ];

    global.game_init_clickmap_load = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_load,        GAME_INIT_LOAD_X, GAME_INIT_LOAD_Y, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.close,            GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, 16, 16,
        GameInitAction.open_update,      GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y, GAME_INIT_UPDATE_W, GAME_INIT_ROW_H,
        GameInitAction.toggle_language,  GAME_INIT_LANG_X, GAME_INIT_LANG_Y, GAME_INIT_LANG_W, GAME_INIT_ROW_H,
        -1
    ];

    /* NET PLAY. START and the mission arrows are here for the host, and simply
       do nothing for the client - which one you are is not known until somebody
       picks, so the panel cannot be laid out differently per role. */
    /* Nothing on the top row. START does nothing until somebody has joined and
       OPTIONS belongs to the screen behind this one, so both were buttons that
       sat there looking pressable and were not. EXIT goes back rather than out,
       which is what a panel opened from somewhere else should do.

       The two things the host does need - choosing the mission and starting it
       - are rows in the list's own style, drawn only when there is a host to do
       them. A control that cannot act should not be on screen. */
    /* Two maps, because the panel is two different screens. The host's
       controls sit exactly where the list of machines is drawn before anyone
       has connected, and one shared map put them on top of it: the arrows ate
       the first three characters of every row and START, at y 76..92, ate the
       whole of the third machine in the list - a click there was caught by the
       START entry, refused because there was no host yet, and never reached
       the row underneath. So: the list's map while picking, the host's map
       once picked. */
    global.game_init_clickmap_netplay = [
        GameInitAction.netplay_host,     NETPLAY_ROW_X, NETPLAY_HOST_Y, 240, NETPLAY_ROW_H,
        GameInitAction.netplay_add,      NETPLAY_ADD_X, NETPLAY_ADD_Y, 280, NETPLAY_ROW_H,
        GameInitAction.close,            GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, 16, 16,
        GameInitAction.open_update,      GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y, GAME_INIT_UPDATE_W, GAME_INIT_ROW_H,
        GameInitAction.toggle_language,  GAME_INIT_LANG_X, GAME_INIT_LANG_Y, GAME_INIT_LANG_W, GAME_INIT_ROW_H,
        -1
    ];

    global.game_init_clickmap_netplay_host = [
        GameInitAction.netplay_mode_mission, NETPLAY_MODE_X,   NETPLAY_MODE_Y, NETPLAY_MODE_MISSION_W, NETPLAY_ROW_H,
        GameInitAction.netplay_mode_custom,  NETPLAY_MODE_CUSTOM_X, NETPLAY_MODE_Y, NETPLAY_MODE_CUSTOM_W, NETPLAY_ROW_H,
        GameInitAction.increment,        NETPLAY_MISSION_X + 152, NETPLAY_MISSION_Y, 40, NETPLAY_ROW_H,
        GameInitAction.decrement,        NETPLAY_MISSION_X,       NETPLAY_MISSION_Y, 40, NETPLAY_ROW_H,
        GameInitAction.netplay_new_map,  NETPLAY_MISSION_X + 200, NETPLAY_MISSION_Y, NETPLAY_NEW_MAP_W, NETPLAY_ROW_H,
        GameInitAction.start_game,       NETPLAY_GO_X,  NETPLAY_GO_Y,  240, NETPLAY_ROW_H,
        GameInitAction.close,            GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, 16, 16,
        GameInitAction.open_update,      GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y, GAME_INIT_UPDATE_W, GAME_INIT_ROW_H,
        GameInitAction.toggle_language,  GAME_INIT_LANG_X, GAME_INIT_LANG_Y, GAME_INIT_LANG_W, GAME_INIT_ROW_H,
        -1
    ];

    /* Joined, waiting for the host: nothing but the way out. */
    global.game_init_clickmap_netplay_client = [
        GameInitAction.close,            GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, 16, 16,
        GameInitAction.open_update,      GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y, GAME_INIT_UPDATE_W, GAME_INIT_ROW_H,
        GameInitAction.toggle_language,  GAME_INIT_LANG_X, GAME_INIT_LANG_Y, GAME_INIT_LANG_W, GAME_INIT_ROW_H,
        -1
    ];
}

/* The panel's vertical layout, in box coordinates. The text is 8 pixels
   tall, so a 10-pixel pitch is as tight as it reads; everything is at a fixed
   y, nothing is placed from where the previous line ended, and the numbers
   below are chosen so that no two things that can be on screen together share
   a pixel row. Order down the box, on the picking screen:
     32  HOST button                       46  "or CLICK a pc ..."
     58  list, six rows, to 118            120 hint about "?"
     130 discovery line                    142 status, up to four lines, to 182
     192 ADD                               228 version caption (the box's own)
   The host's screen reuses 46 for the MISSION / CUSTOM MAP choice, 58 for
   that choice's arrows and 72 for START, with the instructions wrapped from
   86 and stopping short of the discovery line at 130. */
#macro NETPLAY_ROW_X      20
#macro NETPLAY_ROW_H      10
#macro NETPLAY_HOST_Y     32
#macro NETPLAY_LIST_HEAD_Y 46
#macro NETPLAY_ROW_Y      58
#macro NETPLAY_ROW_MAX    6
#macro NETPLAY_HINT_Y     120
#macro NETPLAY_DIAG_Y     130
#macro NETPLAY_STATUS_Y   142

/* The NET PLAY button: the last frame of spr_icon. */
#macro NETPLAY_ICON       318

/* The bottom row, which is now three buttons at an even 40-pixel pitch:
   NET PLAY, LOAD, EXIT. All of them start at y 216, which is the first row
   clear of the map preview (it ends at 215) and of the player boxes.

   NET PLAY was on the top row at x 188, in what looked like a free 32-wide
   slot. It is not free on MISSION: "START MISSION" and "MISSION: n" are drawn
   from x 100 and run straight under it, so the icon sat on top of the words.
   Down here nothing else is competing for the space.

   32-wide icons at 260 and 300, EXIT's 16 at 336, and the frame's inside edge
   at 352. Everything else on this row - the version line, the update note, the
   generation bar and its label - stops at x 252, which is what
   GEN_BAR_W and GEN_LABEL_COLS below are for. */
#macro NETPLAY_BTN_X      260
#macro NETPLAY_BTN_Y      216
#macro GAME_INIT_LOAD_X   300
#macro GAME_INIT_LOAD_Y   216

/* ADD AN ADDRESS, below the list. Its own row rather than the bottom-right
   slot, which is where LOAD is drawn - a button that reads LOAD and adds an
   address is worse than no button. */
#macro NETPLAY_ADD_X      4
#macro NETPLAY_ADD_Y      192

/* The host's two controls, in the list's own style rather than as icons on a
   row that is otherwise empty. Drawn only when there is a host to use them. */
#macro NETPLAY_MISSION_X  20
#macro NETPLAY_MISSION_Y  58
#macro NETPLAY_GO_X       20
#macro NETPLAY_GO_Y       72

/* The host's choice of what to play: a MISSION, or a CUSTOM MAP - a map of
   the host's chosen size from a seed the host can roll again, with the two
   humans on it and nobody else. Two buttons on one row; the one in force is
   amber and the other is a link. The second sits at a fixed x with room for
   the German "[ EIGENE KARTE ]" (sixteen characters), so the clickmap does not
   move with the language. NEW MAP is at +200 on the arrows' row, the slot
   "(done)" has on the mission row, and is sized for "[ NEUE KARTE ]". */
#macro NETPLAY_MODE_X          20
#macro NETPLAY_MODE_Y          46
#macro NETPLAY_MODE_MISSION_W  88
#macro NETPLAY_MODE_CUSTOM_X   124
#macro NETPLAY_MODE_CUSTOM_W   128
#macro NETPLAY_NEW_MAP_W       112

/* How many characters fit on a line here. gfx_draw_string advances 8 pixels a
   character and nothing about it wraps or clips, so a line that is too long
   simply keeps drawing out through the frame and onto the map behind - which is
   what every line of this panel was doing. Text starts at x 20 and the frame
   takes the last few pixels, so 40 is the honest number. */
#macro NETPLAY_COLS       40

/* EXIT, hard into the bottom-right corner of the frame. It was drawn by
   draw_box_icon(38, 208), which lands at (324, 224), while every clickmap said
   (324, 216) - so the region you could press sat eight pixels above the icon
   you could see. One pair of numbers for both now, used by the drawing and by
   all four clickmaps, which is what stops them drifting apart again. The frame
   is 8 pixels thick and the icon is 16, so on a 360x254 box the corner is
   (336, 230). */
#macro GAME_INIT_EXIT_X   336
#macro GAME_INIT_EXIT_Y   230

/* Two things on the version rows that can be clicked, both text rather than
   icons, both lit lime through link_colour like the NET PLAY panel's links:

   The language, on the version row itself. "SETTLERSGM 1.0.6.0" is eighteen
   characters from column 0, so the name goes at column 20 (x 180), seven
   characters, ending at 236 - clear of NET PLAY at 260. Clicking it switches
   to the other language on the spot and remembers it (scr_locale.gml).

   The update note, on the row under it, when there is a newer build than this
   one. It flashes to be noticed and opens the itch page when clicked. The row
   is the same one the load status and the generation label use, so the note
   is only drawn - and only clickable - when neither of those has it.

   Both bands are 12 pixels tall around 8-pixel text, and the same numbers are
   used by the drawing and by all six clickmaps - the NET PLAY panel draws the
   version rows too - so they cannot drift apart. The y values are box
   coordinates: draw_box_string(0, 212) lands at y 228. */
#macro GAME_INIT_ROW_H    12
#macro GAME_INIT_LANG_X   180
#macro GAME_INIT_LANG_Y   226
#macro GAME_INIT_LANG_W   56
#macro GAME_INIT_UPDATE_X 20
#macro GAME_INIT_UPDATE_Y 238
#macro GAME_INIT_UPDATE_W 232

/* The map generation bar, along the bottom of the panel (which is 360x254).
   It shares this row with the NET PLAY and LOAD buttons, so it stops at x 252
   - 20 + 232 - which leaves eight clear pixels before NET PLAY at 260.

   GEN_LABEL_COLS is the same limit for the label above it, in characters:
   gfx_draw_string neither wraps nor clips, so a phase name longer than the row
   would simply keep drawing out across the buttons. "GENERATING - TREES AND
   STONE" is the longest there is at 28, and the label is cut to 29 so that a
   phase name added later cannot quietly start painting over LOAD. */
#macro GEN_BAR_X          20
#macro GEN_BAR_LABEL_Y    228
#macro GEN_BAR_Y          240
#macro GEN_BAR_W          232
#macro GEN_BAR_H          8
#macro GEN_LABEL_COLS     29

/* How far down the stone wall behind the panel is taken, 0 for the art as it
   comes. A wash rather than a repaint, so the courses and the carving are all
   still there - there is just less of a fight between them and the text. */
#macro GAME_INIT_BG_DARKEN  0.3

/* The three levels the NET PLAY panel writes in, in one place rather than
   rebuilt from six hex numbers every time the panel is drawn:
     TEXT  something to read or to click
     DIM   an explanation, a machine that is not hosting, a diagnostic
     NOTE  status, and anything the panel is waiting on
   Nothing else on the box uses them - the rest is the original's green on
   black through draw_box_string. */
#macro NETPLAY_COL_TEXT   make_colour_rgb(0xff, 0xff, 0xff)
#macro NETPLAY_COL_DIM    make_colour_rgb(0xa0, 0xa0, 0xb0)
#macro NETPLAY_COL_NOTE   make_colour_rgb(0xff, 0xff, 0x99)

/* A fourth: the colour of something you can actually click. This panel is
   built out of text rather than buttons, so nothing about a line says whether
   pressing it will do anything - HOST, a machine in the list, ADD, the mission
   arrows and START all looked exactly like the sentences explaining them.

   Lime for "this does something", and NETPLAY_COL_TEXT while the pointer is on
   it. Every one of them goes through link_colour with the SAME rectangle the
   clickmap uses, so what lights up under the pointer is what will be pressed -
   if those ever disagree, it is now visible rather than silent. */
#macro NETPLAY_COL_LINK   make_colour_rgb(0x7c, 0xff, 0x3c)

/// Port of Random::Random() (random.cc lines 27-33): seed from the clock
/// and consume one value.
function game_init_random_default() {
    var _rnd = new RandomState(irandom(0xFFFF), irandom(0xFFFF), irandom(0xFFFF));
    _rnd.next_random();
    return _rnd;
}

/// RandomInput : TextInput : GuiObject  (game-init.cc lines 36-83 plus the
/// parts of TextInput (text-input.cc) it relies on).
function RandomInput() : GuiObject() constructor {
    game_init_init_tables();

    // TextInput members
    text = "";
    max_length = 0;
    filter = undefined;
    draw_focus = true;
    color_focus = global.game_init_color_focus;
    color_text = global.game_init_color_green;
    color_background = global.game_init_color_black;

    // RandomInput members
    saved_text = "";

    // ------------------------------------------------------------ TextInput

    static set_text = function(_text) {
        text = _text;
        set_redraw();
    };

    static get_text = function() {
        return text;
    };

    static set_max_length = function(_max_len) {
        max_length = _max_len;
        if (max_length != 0) {
            if (string_length(text) > max_length) {
                text = string_copy(text, 1, max_length);
            }
        }
    };

    static set_filter = function(_filter) {
        filter = _filter;
    };

    static internal_draw = function() {
        gfx_fill_rect(0, 0, width, height, color_background);
        if (draw_focus && focused) {
            gfx_draw_rect(0, 0, width, height, color_focus);
        }
        var _ch_width = width div 8;
        var _str = text;
        var _cx = 0;
        var _cy = 0;
        if (draw_focus) {
            _cx = 1;
            _cy = 1;
        }
        while (string_length(_str) > 0) {
            var _substr = string_copy(_str, 1, _ch_width);
            _str = string_delete(_str, 1, _ch_width);
            gfx_draw_string(_cx, _cy, _substr, color_text, -1);
            _cy += 8;
        }
    };

    /// TextInput::handle_key_pressed(char key, int modifier); _key is the
    /// ascii code (8 = backspace).
    static handle_key_pressed = function(_key, _modifier) {
        if (!focused) {
            return false;
        }

        if ((max_length != 0) && (string_length(text) >= max_length)) {
            return true;
        }

        if ((_key == 8) && (string_length(text) > 0)) {
            text = string_copy(text, 1, string_length(text) - 1);
            set_redraw();
            return true;
        }

        if (filter != undefined) {
            if (!filter(_key, self)) {
                return true;
            }
        }

        text += chr(_key);

        set_redraw();

        return true;
    };

    // ---------------------------------------------------------- RandomInput

    /// static bool text_input_filter(const char key, TextInput *text_input)
    static text_input_filter = function(_key, _text_input) {
        if (_key < ord("1") || _key > ord("8")) {
            return false;
        }

        if (string_length(_text_input.get_text()) > 16) {
            return false;
        }

        return true;
    };

    /// _rnd: RandomState
    static set_random = function(_rnd) {
        var _str = random_state_to_string(_rnd);
        set_text(_str);
    };

    /// Returns a RandomState built from the 16-character text.
    static get_random = function() {
        return random_state_from_string(text);
    };

    static handle_click_left = function(_cx, _cy) {
        // TextInput::handle_click_left(cx, cy)
        set_focused();
        saved_text = text;
        text = "";
        return true;
    };

    static handle_focus_loose = function() {
        // TextInput::handle_focus_loose()
        focused = false;
        set_redraw();
        if ((string_length(text) < 16) && (string_length(saved_text) == 16)) {
            text = saved_text;
            saved_text = "";
        }
        return true;
    };

    // Constructor body: RandomInput()
    set_filter(text_input_filter);
    set_size(34, 34);
    set_max_length(16);
}

/// GameInitBox : GuiObject  (C++: explicit GameInitBox(Interface *interface))
function GameInitBox(_interface) : GuiObject() constructor {
    game_init_init_tables();

    interface = _interface;

    game_type = GameType.custom;
    game_mission = 0;

    /* Which screen NET PLAY was opened from, so the same button goes back to
       it rather than always landing on one of them. */
    netplay_return_type = GameType.custom;

    /* The host's alternative to a mission: a custom map of netplay_size from
       netplay_seed, two humans and no AI. Only these two numbers are the map;
       net_custom_game_info builds the same GameInfo from them on both
       machines. The seed is rolled here and again by NEW MAP. */
    netplay_custom = false;
    netplay_size = NET_CUSTOM_SIZE_MIN;
    netplay_seed = game_init_random_default();

    custom_mission = undefined;
    mission = undefined;

    random_input = new RandomInput();
    map = undefined;
    minimap = new Minimap(undefined);
    file_list = new ListSavedFiles();

    static draw_box_icon = function(_ix, _iy, _sprite) {
        gfx_draw_sprite(8 * _ix + 20, _iy + 16, Asset.icon, _sprite);
    };

    static draw_box_string = function(_sx, _sy, _str) {
        gfx_draw_string(8 * _sx + 20, _sy + 16, _str,
                        global.game_init_color_green, global.game_init_color_black);
    };

    /// The stone wall behind the panel: 40x8 strips of it, sprites 290 to 294,
    /// stepped backwards a row at a time and wrapped round so the courses do
    /// not line up into columns.
    ///
    /// Then a wash of black over the whole thing. The art is the original's and
    /// is not being repainted; it is simply brighter than the text sitting on
    /// it wants, and every line on this panel - white, grey, amber - reads
    /// better against a darker wall. GAME_INIT_BG_DARKEN is the one number to
    /// change. The frame, the icons and the text are all drawn afterwards, so
    /// only the wall is taken down.
    static draw_bg = function() {   // C++ draw_background (legacy GM built-in name)
        var _icon = 290;
        for (var _by = 0; _by < height; _by += 8) {
            for (var _bx = 0; _bx < width; _bx += 40) {
                gfx_draw_sprite(_bx, _by, Asset.icon, _icon);
            }
            _icon--;
            if (_icon < 290) {
                _icon = 294;
            }
        }

        if (GAME_INIT_BG_DARKEN > 0) {
            draw_set_alpha(GAME_INIT_BG_DARKEN);
            gfx_fill_rect(0, 0, width, height, global.game_init_color_black);
            draw_set_alpha(1);
        }
    };

    /* Get the sprite number for a face. */
    static get_player_face_sprite = function(_face) {
        if (_face != 0) {
            return 0x10b + _face;
        }
        return 0x119; /* sprite_face_none */
    };

    /// Break a line to fit the panel, on spaces where it can and mid-word when
    /// a single word is longer than the line. Returns an array of lines.
    static netplay_wrap = function(_str, _cols) {
        var _lines = [];
        var _rest = _str;

        while (string_length(_rest) > _cols) {
            /* The last space that still fits. Walking back from the limit means
               a word is only split when it is longer than a whole line. */
            var _space = 0;
            for (var _i = _cols + 1; _i >= 2; _i--) {
                if (string_char_at(_rest, _i) == " ") {
                    _space = _i;
                    break;
                }
            }

            /* _take is how much of the line to keep, _drop how much to remove
               from the front afterwards. They differ by the space, which is
               kept out of both lines rather than starting the next one. Getting
               this wrong loses a character per break, silently, and only in the
               unsplittable-word case. */
            var _take = _cols;
            var _drop = _cols;
            if (_space > 1) {
                _take = _space - 1;
                _drop = _space;
            }

            array_push(_lines, string_copy(_rest, 1, _take));
            _rest = string_delete(_rest, 1, _drop);
        }

        array_push(_lines, _rest);
        return _lines;
    };

    /// Is the pointer inside this rectangle of the box?
    ///
    /// get_screen_position rather than the gfx origin: it is what the drawing
    /// itself is offset by, so the two cannot disagree about where the box is,
    /// and it works whether or not a draw is in progress. mouse_x and mouse_y
    /// are room coordinates, which GameMaker has already divided the window
    /// scaling out of - the same coordinates the click arrives in.
    static box_hover = function(_hx, _hy, _hw, _hh) {
        var _sp = get_screen_position();
        var _mx = mouse_x - _sp[0];
        var _my = mouse_y - _sp[1];
        return (_mx >= _hx && _mx < _hx + _hw &&
                _my >= _hy && _my < _hy + _hh);
    };

    /// The colour for something clickable: lime, or white while the pointer is
    /// over it. Pass the rectangle the clickmap uses for it.
    static link_colour = function(_hx, _hy, _hw, _hh) {
        if (box_hover(_hx, _hy, _hw, _hh)) {
            return NETPLAY_COL_TEXT;
        }
        return NETPLAY_COL_LINK;
    };

    /// Draw a line, wrapped, from _y downwards. Returns the y after the last
    /// line so the next thing can carry on from there.
    static netplay_draw_wrapped = function(_x, _y, _str, _colour) {
        var _lines = netplay_wrap(_str, NETPLAY_COLS);
        for (var _i = 0; _i < array_length(_lines); _i++) {
            gfx_draw_string(_x, _y + _i * NETPLAY_ROW_H, _lines[_i], _colour, -1);
        }
        return _y + array_length(_lines) * NETPLAY_ROW_H;
    };

    /// The NET PLAY panel.
    ///
    /// One pc clicks HOST; its beacon then says so, and the other pc sees it
    /// marked HOSTING and clicks it to JOIN. That is the F7 / F8 model the
    /// keys had before there was a panel, which worked - the roles are
    /// declared, not raced for.
    static draw_netplay = function() {
        var _white = NETPLAY_COL_TEXT;
        var _grey  = NETPLAY_COL_DIM;
        var _amber = NETPLAY_COL_NOTE;

        draw_box_string(0, 2, L("Net play"));

        if (net_is_running()) {
            /* In a game already - the panel is just a status board now. */
            netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_HOST_Y,
                                 "In a game. " + net_status_line(), _amber);
            return;
        }

        /* Every heading on this panel is ONE line of forty characters, and
           every row below it is at a fixed y. Nothing here is placed from
           where the previous thing ended, because that is how a heading that
           wrapped came to be drawn through the mission row. */

        if (global.net_role == NetRole.host) {
            /* HOSTING. Before player 2 arrives the only control is the
               mission choice; START appears when there is somebody to start
               with. */
            if (global.net_socket >= 0) {
                gfx_draw_string(NETPLAY_ROW_X, NETPLAY_HOST_Y,
                                L("YOU ARE HOSTING - player 2 has joined"), _amber, -1);
            } else {
                gfx_draw_string(NETPLAY_ROW_X, NETPLAY_HOST_Y,
                                L("YOU ARE HOSTING - waiting for player 2"), _amber, -1);
            }

            /* What to play. The choice in force is amber and stays amber
               under the pointer - pressing it again does nothing, so it must
               not light up like something that would. The other is a link. */
            var _mission_colour = _amber;
            var _custom_colour = link_colour(NETPLAY_MODE_CUSTOM_X, NETPLAY_MODE_Y,
                                             NETPLAY_MODE_CUSTOM_W, NETPLAY_ROW_H);
            if (netplay_custom) {
                _mission_colour = link_colour(NETPLAY_MODE_X, NETPLAY_MODE_Y,
                                              NETPLAY_MODE_MISSION_W, NETPLAY_ROW_H);
                _custom_colour = _amber;
            }
            gfx_draw_string(NETPLAY_MODE_X, NETPLAY_MODE_Y, L("[ MISSION ]"),
                            _mission_colour, -1);
            gfx_draw_string(NETPLAY_MODE_CUSTOM_X, NETPLAY_MODE_Y, L("[ CUSTOM MAP ]"),
                            _custom_colour, -1);

            /* Four draws where there were two, because the parts of this row
               are not the same kind of thing. Only the first 40 pixels - the
               five characters of "[ < ]" - are the decrement button, and only
               40 more at +152 are the increment; lighting the whole row would
               promise a click that lands nowhere.

               The mission name sits between them, in the 96 pixels from +56 to
               +152, which is twelve characters - enough for "MISSION 10". The
               "(done)" mark goes after the second arrow rather than after the
               name, where it used to run 48 pixels straight through it once the
               mission number reached two digits.

               On a custom map the same arrows step the size and the slot after
               them is the NEW MAP button, which rolls another seed. */
            gfx_draw_string(NETPLAY_MISSION_X, NETPLAY_MISSION_Y, "[ < ]",
                            link_colour(NETPLAY_MISSION_X, NETPLAY_MISSION_Y,
                                        40, NETPLAY_ROW_H), -1);
            gfx_draw_string(NETPLAY_MISSION_X + 152, NETPLAY_MISSION_Y, "[ > ]",
                            link_colour(NETPLAY_MISSION_X + 152,
                                        NETPLAY_MISSION_Y, 40, NETPLAY_ROW_H),
                            -1);
            if (netplay_custom) {
                gfx_draw_string(NETPLAY_MISSION_X + 56, NETPLAY_MISSION_Y,
                                LF("SIZE {0}", netplay_size), _white, -1);
                gfx_draw_string(NETPLAY_MISSION_X + 200, NETPLAY_MISSION_Y,
                                L("[ NEW MAP ]"),
                                link_colour(NETPLAY_MISSION_X + 200, NETPLAY_MISSION_Y,
                                            NETPLAY_NEW_MAP_W, NETPLAY_ROW_H), -1);
            } else {
                gfx_draw_string(NETPLAY_MISSION_X + 56, NETPLAY_MISSION_Y,
                                "MISSION " + string(game_mission + 1), _white, -1);
                if (progress_mission_is_done(game_mission)) {
                    gfx_draw_string(NETPLAY_MISSION_X + 200, NETPLAY_MISSION_Y,
                                    L("(done)"), _grey, -1);
                }
            }

            if (global.net_socket >= 0) {
                gfx_draw_string(NETPLAY_GO_X, NETPLAY_GO_Y,
                                L("[ CLICK HERE TO START ]"),
                                link_colour(NETPLAY_GO_X, NETPLAY_GO_Y,
                                            240, NETPLAY_ROW_H), -1);
                if (netplay_custom) {
                    netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_GO_Y + 14,
                                         L("CLICK < or > to set the map size and"
                                           + " NEW MAP to roll another, then CLICK"
                                           + " START. It begins on both pcs at"
                                           + " once."), _amber);
                } else {
                    netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_GO_Y + 14,
                                         L("CLICK < or > to choose the mission, then"
                                           + " CLICK START. It begins on both pcs at"
                                           + " once."), _amber);
                }
            } else {
                netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_GO_Y,
                                     L("On the OTHER pc: open NET PLAY, find this"
                                       + " pc in the list marked HOSTING, and"
                                       + " CLICK it. Nothing more to do here"
                                       + " until then."), _grey);
            }

            netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_DIAG_Y,
                                 net_discovery_summary(), _grey);
            if (net_status_line() != "") {
                netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_STATUS_Y,
                                     net_status_line(), _amber);
            }
            return;
        }

        if (global.net_role == NetRole.client) {
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_HOST_Y,
                            L("JOINED - you are player 2"), _amber, -1);
            netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_MODE_Y,
                                 LF("Host is {0}. It picks"
                                    + " the mission and CLICKS START. Nothing to"
                                    + " click on this pc - just wait, the game"
                                    + " opens by itself.",
                                    net_addr_label(global.net_peer_ip)), _grey);

            netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_DIAG_Y,
                                 net_discovery_summary(), _grey);
            if (net_status_line() != "") {
                netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_STATUS_Y,
                                     net_status_line(), _amber);
            }
            return;
        }

        /* Nobody's yet. Two ways in: be the host, or join one. */
        gfx_draw_string(NETPLAY_ROW_X, NETPLAY_HOST_Y,
                        L("[ CLICK HERE TO HOST A GAME ]"),
                        link_colour(NETPLAY_ROW_X, NETPLAY_HOST_Y,
                                    240, NETPLAY_ROW_H), -1);
        gfx_draw_string(NETPLAY_ROW_X, NETPLAY_LIST_HEAD_Y,
                        L("or CLICK a pc below that is HOSTING:"), _white, -1);

        var _count = net_peer_count();
        if (_count == 0) {
            netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_ROW_Y,
                                 L("Nobody yet. Open NET PLAY on the other pc too"
                                   + " and it appears here."), _grey);

            /* Discovery needs the UDP port. Two copies on ONE machine cannot
               both have it, and a firewall can refuse it outright - in either
               case the list will never fill itself, so say so here rather than
               leave somebody waiting for a row that cannot arrive. */
            if (!global.net_udp_bound) {
                netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_ROW_Y + 3 * NETPLAY_ROW_H,
                                     L("This pc can't listen for others (second"
                                       + " copy running?). CLICK ADD below and"
                                       + " type the other pc's IP."), _amber);
            } else {
                netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_ROW_Y + 3 * NETPLAY_ROW_H,
                                     L("Not showing up? CLICK ADD below and type"
                                       + " the other pc's IP."), _grey);
            }
        }

        var _rows = min(_count, NETPLAY_ROW_MAX);
        for (var _i = 0; _i < _rows; _i++) {
            var _peer = net_peer_at(_i);
            var _ry = NETPLAY_ROW_Y + _i * NETPLAY_ROW_H;

            /* What the row says is what its beacon last said. A pc that is
               hosting is the one to click; one that is online and not hosting
               needs its owner to click HOST first; one never heard from could
               be anything, so it can be tried. Each of those is a different
               line, so nobody has to guess which they are looking at. */
            /* A row worth clicking is lime and lights up under the pointer,
               over the same 300 pixels handle_click_left reads. A row that is
               online and not hosting stays grey: clicking it only produces a
               line of text telling you to go and press HOST over there, and a
               control that cannot do the thing it names should not look like
               one that can. */
            var _colour = _grey;
            var _lead = "  ";
            var _tail = L("  online, not hosting");
            if (!net_peer_is_live(_peer)) {
                _colour = link_colour(NETPLAY_ROW_X, _ry, 300, NETPLAY_ROW_H);
                _lead = L("[CLICK to JOIN] ");
                _tail = "  ?";
            } else if (_peer.hosting == NET_HOSTING_OPEN) {
                _colour = link_colour(NETPLAY_ROW_X, _ry, 300, NETPLAY_ROW_H);
                _lead = L("[CLICK to JOIN] ");
                _tail = L("  HOSTING");
            } else if (_peer.hosting == NET_HOSTING_FULL) {
                _tail = L("  hosting, full");
            }

            /* net_peer_label, never _peer.ip: a private address is printed
               as it is, a routable one is replaced by its tag. See
               net_addr_label in scr_net.gml for why. */
            gfx_draw_string(NETPLAY_ROW_X, _ry,
                            _lead + net_peer_label(_peer) + _tail, _colour, -1);
        }

        if (_count > 0) {
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_HINT_Y,
                            L("? = not heard from yet. CLICK it anyway."), _grey, -1);
        }

        /* What discovery has actually managed, always, on both machines.
           Sending but hearing nothing is a blocked port; hearing packets but
           listing nobody is a fault in here. The two look identical from an
           empty list and want opposite fixes, and comparing the two machines'
           lines says which end is the quiet one. */
        netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_DIAG_Y,
                             net_discovery_summary(), _grey);

        if (global.net_ip_prompt && global.net_ip_prompt_mode == "add") {
            /* The typing happens HERE, on the panel that asked for it, not in
               small yellow text in the corner of the screen behind it. */
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_STATUS_Y,
                            L("TYPE the other pc's IP, then press ENTER:"),
                            _amber, -1);
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_STATUS_Y + NETPLAY_ROW_H,
                            "> " + global.net_ip_text + "_", _white, -1);
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_STATUS_Y + 2 * NETPLAY_ROW_H,
                            L("(ESC cancels)"), _grey, -1);
        } else {
            gfx_draw_string(NETPLAY_ADD_X, NETPLAY_ADD_Y,
                            L("[ CLICK to ADD the other pc's IP ]"),
                            link_colour(NETPLAY_ADD_X, NETPLAY_ADD_Y,
                                        280, NETPLAY_ROW_H), -1);

            if (net_status_line() != "") {
                netplay_draw_wrapped(NETPLAY_ROW_X, NETPLAY_STATUS_Y,
                                     net_status_line(), _amber);
            }
        }
    };

    /// Is the update note on screen? The same answer for drawing it and for
    /// clicking it, so a click can never land on a note that is not there.
    /// Its row is shared: the generation bar owns it while a map is being
    /// built and the load status owns it whenever there is something to say
    /// about a save.
    static update_note_shown = function() {
        if (gen_active) {
            return false;
        }
        if (!global.update_available) {
            return false;
        }
        if (load_status != "") {
            return false;
        }
        return true;
    };

    static internal_draw = function() {
        draw_bg();

        /* Popup frame art rather than frame_top: plain planks with a cap at
           each end, no studs partway along, and only 8px thick. */
        gfx_draw_frame_box(0, 0, width, height);

        /* LOAD is a real button now - icon 316, the game's own 32x32 LOAD
           plaque - drawn beside EXIT from the layout below rather than as a
           white label painted on a black rectangle in the middle of the bottom
           row. That was scaffolding, and it was sitting on the only stretch of
           that row wide enough for the version caption. */

        /* Full label of the highlighted save, in one fixed place above the
           list so the rows stay short and the date does not jump about. */
        if (game_type == GameType.load) {
            var _sel = file_list.get_selected_slot();
            if (_sel >= 0 && savegame_slot_exists(_sel)) {
                gfx_draw_string(20, 44, savegame_slot_label(_sel),
                                make_colour_rgb(0xff, 0xff, 0xff), -1);
            }
        }

        /* Below the list, not under it: file_list is 160x160 at (20,55) and
           paints a black background over everything from y=55 to y=215, so a
           status drawn inside that range was never visible. */
        /* Cut to the row's width like everything else down here. Most of these
           are short, but savegame_last_error() is whatever the loader had to
           say, and a long one would run out across LOAD and EXIT. */
        if (load_status != "") {
            var _status = load_status;
            if (string_length(_status) > GEN_LABEL_COLS) {
                _status = string_copy(_status, 1, GEN_LABEL_COLS);
            }
            gfx_draw_string(20, 240, _status,
                            make_colour_rgb(0xff, 0xff, 0x99), -1);
        }

        /* START and OPTIONS, except on NET PLAY - see the clickmap comment. */
        if (game_type != GameType.netplay) {
            var _layout = global.game_init_layout;
            var _i = 0;
            while (_layout[_i] >= 0) {
                draw_box_icon(_layout[_i + 1], _layout[_i + 2], _layout[_i]);
                _i += 3;
            }
        }

        /* NET PLAY, on the top row. Not on the panel itself: EXIT is the way
           back from there, so a second way out would only be another button
           taking up the room the text needs. */
        if (game_type != GameType.netplay) {
            gfx_draw_sprite(NETPLAY_BTN_X, NETPLAY_BTN_Y, Asset.icon, NETPLAY_ICON);
        }

        if (game_type == GameType.netplay) {
            draw_netplay();
        }

        /* Game type settings */
        switch (game_type) {
            case GameType.mission: {
                draw_box_icon(5, 0, 260);  // Game type

                var _level = string(game_mission + 1);

                draw_box_string(10, 2, L("Start mission"));
                draw_box_string(10, 18, L("Mission:"));
                draw_box_string(20, 18, _level);

                /* Not in the original: mark a mission already won, so you can
                   step through the list and see where you got to rather than
                   having to remember. progress_mission_is_done reads a cached
                   array, so asking every frame costs nothing. */
                if (progress_mission_is_done(game_mission)) {
                    draw_box_string(24, 18, L("Complete"));
                }


                draw_box_icon(33, 0, 237);  // Up button
                draw_box_icon(33, 16, 240);  // Down button

                break;
            }
            case GameType.custom: {
                draw_box_icon(5, 0, 263);  // Game type

                var _str_map_size = string(mission.get_map_size());

                draw_box_string(10, 2, L("New game"));
                draw_box_string(10, 18, L("Mapsize:"));
                draw_box_string(18, 18, _str_map_size);

                draw_box_icon(25, 0, 265);

                break;
            }
            case GameType.load: {
                draw_box_icon(5, 0, 316);  // Game type

                draw_box_string(10, 2, L("Load game"));

                break;
            }
        }

        /* Game info. Not on NET PLAY: the faces and their supply bars are for
           setting up a game, which has already happened on the screen behind
           this one - here they are furniture sitting on top of the list. */
        if (game_type != GameType.load && game_type != GameType.netplay) {
            var _bx = 0;
            var _by = 0;
            for (var _p = 0; _p < GAME_MAX_PLAYER_COUNT; _p++) {
                draw_player_box(_p, 10 * _bx, 40 + _by * 80);
                _bx++;
                if (_p == 1) {
                    _by++;
                    _bx = 0;
                }
            }
        }

        /* Program name and version, and - when the repository says there is a
           newer build than this one - a word about that on the line UNDER it
           rather than squeezed in beside it. A whole line to itself is 29
           columns instead of eleven, so the new version number always fits and
           no longer has to be dropped to keep the word.

           That second line is shared, and this is the last thing with a claim
           on it. The generation bar and its label own it while a map is being
           built, and the version line above stands down with this one then; the
           load status owns it whenever there is something to say about a save.
           So the note is drawn only when neither of those is using the row. It
           is the one thing here that can wait - the update is still there next
           time the panel opens. */
        if (!gen_active) {
            draw_box_string(0, 212, GAME_INIT_VERSION + " " + game_version());

            /* The language, as a button: lime, white under the pointer, over
               the same band the clickmap reads. See the macros. */
            gfx_draw_string(GAME_INIT_LANG_X, GAME_INIT_LANG_Y + 2, locale_name(),
                            link_colour(GAME_INIT_LANG_X, GAME_INIT_LANG_Y,
                                        GAME_INIT_LANG_W, GAME_INIT_ROW_H),
                            global.game_init_color_black);

            if (update_note_shown()) {
                var _note = LF("UPDATE {0} - CLICK HERE", global.update_latest);
                if (string_length(_note) > GEN_LABEL_COLS) {
                    _note = string_copy(_note, 1, GEN_LABEL_COLS);
                }

                /* Flashing between the panel's green and the note colour, so
                   the eye is drawn to it; white while the pointer is on it,
                   like every other link, because it is one. */
                var _colour = global.game_init_color_green;
                if ((current_time div UPDATE_FLASH_MS) mod 2 == 0) {
                    _colour = NETPLAY_COL_NOTE;
                }
                if (box_hover(GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y,
                              GAME_INIT_UPDATE_W, GAME_INIT_ROW_H)) {
                    _colour = NETPLAY_COL_TEXT;
                }
                gfx_draw_string(GAME_INIT_UPDATE_X, GAME_INIT_UPDATE_Y + 2, _note,
                                _colour, global.game_init_color_black);
            }
        }

        /* Bottom-row buttons: NET PLAY at 260, LOAD at 300, EXIT at 336, all
           at y 216, which is the first row clear of the map preview above.
           LOAD is 32x32 against EXIT's 16x16, so both are placed by their own
           top-left rather than by icon columns - see the macros. */
        if (game_type != GameType.netplay) {
            gfx_draw_sprite(GAME_INIT_LOAD_X, GAME_INIT_LOAD_Y, Asset.icon, 316);
        }
        gfx_draw_sprite(GAME_INIT_EXIT_X, GAME_INIT_EXIT_Y, Asset.icon, 60);

        /* Last, so it sits over the panel rather than under it. Draws nothing
           unless a map is actually being generated. */
        draw_map_progress();
    };

    static draw_player_box = function(_player, _bx, _by) {
        var _layout = global.game_init_player_layout;
        var _i = 0;
        while (_layout[_i] >= 0) {
            draw_box_icon(_bx + _layout[_i + 1], _by + _layout[_i + 2], _layout[_i]);
            _i += 3;
        }

        _by += 8;
        _bx += 1;

        var _face = 0;
        if (_player < mission.get_player_count()) {
            _face = mission.get_player(_player).get_face();
        }

        draw_box_icon(_bx, _by, get_player_face_sprite(_face));
        draw_box_icon(_bx + 5, _by, 282);
        if (game_type == GameType.custom) {
            draw_box_icon(_bx + 4, _by, 308);
            if (_face == 0) {
                draw_box_icon(_bx + 5, _by, 287);
            } else {
                draw_box_icon(_bx + 5, _by, 259);
            }
        }

        if (_player < mission.get_player_count()) {
            _bx *= 8;

            var _pi = mission.get_player(_player);
            var _supplies = _pi.get_supplies();
            // (height 0 rects are skipped: gfx_fill_rect would draw a line)
            if (_supplies > 0) {
                gfx_fill_rect(_bx + 64, _by + 76 - _supplies, 4, _supplies,
                              global.game_init_color_supplies);
            }

            var _intelligence = _pi.get_intelligence();
            if (_intelligence > 0) {
                gfx_fill_rect(_bx + 70, _by + 76 - _intelligence, 4, _intelligence,
                              global.game_init_color_intelligence);
            }

            var _reproduction = _pi.get_reproduction();
            if (_reproduction > 0) {
                gfx_fill_rect(_bx + 76, _by + 76 - _reproduction, 4, _reproduction,
                              global.game_init_color_reproduction);
            }
        }
    };

    /// Switches to a game type (body of the inner switch of
    /// ActionToggleGameType).
    static set_game_type = function(_game_type) {
        game_type = _game_type;
        switch (game_type) {
            case GameType.mission: {
                mission = game_info_get_mission(game_mission);
                random_input.set_displayed(false);
                file_list.set_displayed(false);
                minimap.set_displayed(true);
                generate_map_preview();
                break;
            }
            case GameType.custom: {
                mission = custom_mission;
                minimap.set_displayed(true);
                random_input.set_displayed(true);
                random_input.set_random(custom_mission.get_random_base());
                file_list.set_displayed(false);
                generate_map_preview();
                break;
            }
            case GameType.load: {
                random_input.set_displayed(false);
                minimap.set_displayed(true);
                file_list.set_displayed(true);
                break;
            }
            case GameType.netplay: {
                random_input.set_displayed(false);
                file_list.set_displayed(false);
                /* The map preview is about which map you are starting, and that
                   was chosen on the screen behind this one. It is also sitting
                   exactly where the list of machines wants to be. */
                minimap.set_displayed(false);
                /* The mission the host would start. Netplay uses the mission
                   list, so it needs a valid mission object the moment the panel
                   opens rather than the first time an arrow is pressed. */
                mission = game_info_get_mission(game_mission);
                net_lobby_open();
                break;
            }
        }

        /* Leaving the panel stops the shouting and closes the door, unless a
           game is already running on it. A connection that has not become a
           game goes too - on both machines, since the other end sees the
           drop and returns to its own lobby. Before this, the host pressing
           EXIT with somebody joined was read by obj_game as F7's "lobby
           closed, start mission 1 now", which is a surprising thing for a
           button marked EXIT to do. */
        if (game_type != GameType.netplay) {
            global.net_ip_prompt = false;
            if (net_is_active() && !net_is_running()) {
                net_close(L("left net play"));
            }
            net_lobby_close();
        }
    };

    /// GameInitBox::apply_random(Random rnd) (declared in game-init.h; the
    /// body is what ActionApplyRandom does with a given random state).
    static apply_random = function(_rnd) {
        custom_mission.set_random_base(_rnd);
        mission = custom_mission;
        generate_map_preview();
    };

    /// Load whatever the list has highlighted. Failures are reported in the
    /// box rather than only to the debug log, which is easy to miss.
    static load_selected_save = function() {
        if (file_list.get_selected_slot() < 0) {
            load_status = L("No save selected");
            set_redraw();
            return;
        }

        var _slot = file_list.get_selected_slot();
        var _path = file_list.get_selected();
        if (!file_exists(_path)) {
            load_status = LF("Slot {0} is empty", _slot + 1);
            set_redraw();
            return;
        }

        var _loaded = game_store_load(_path);
        if (_loaded == undefined) {
            load_status = savegame_last_error();
            if (load_status == "") {
                load_status = L("Save could not be read");
            }
            set_redraw();
            return;
        }

        var _loaded_map = _loaded.get_map();
        if (_loaded_map == undefined || !is_struct(_loaded_map) ||
            !variable_struct_exists(_loaded_map, "geom")) {
            load_status = L("Save has no usable map");
            set_redraw();
            return;
        }

        if (interface == undefined) {
            return;
        }

        load_status = L("Loading...");
        set_redraw();
        interface.request_game(_loaded);
    };

    static handle_action = function(_action) {
        switch (_action) {
            case GameInitAction.start_game: {
                if (game_type == GameType.netplay) {
                    /* Only the host starts, and only once somebody is actually
                       connected. The client's START does nothing at all, which
                       is correct: it has nothing to tell the other machine. */
                    if (global.net_role != NetRole.host || global.net_socket < 0) {
                        break;
                    }
                    /* And only once player 2 has said which build it is and it
                       matched ours - the reason goes on the panel, and the
                       panel stays open to show it. */
                    if (!net_host_may_start()) {
                        break;
                    }
                    net_lobby_close();
                    if (netplay_custom) {
                        net_host_start_game(interface, NET_CUSTOM_MISSION,
                                            netplay_size, netplay_seed);
                    } else {
                        net_host_start_game(interface, game_mission, 0,
                                            new RandomState(0, 0, 0));
                    }
                    interface.close_game_init();
                    break;
                }

                if (game_type == GameType.load) {
                    load_selected_save();
                    return;
                }

                // GameManager::start_game(mission)
                var _game = new Game();
                if (mission.instantiate(_game) == undefined) {
                    return;
                }

                /* Which mission this is, so that winning it can tick it off in
                   the list. A custom game keeps the constructor's -1 and so
                   cannot tick anything off. Recording it as CURRENT is
                   Interface.set_game's job, for every game that becomes
                   current, this one included. */
                if (game_type == GameType.mission) {
                    _game.mission_index = game_mission;
                    show_debug_message("game init: starting mission " +
                                       string(game_mission + 1) +
                                       " (index " + string(game_mission) + ")");
                }

                interface.on_new_game(_game);
                interface.close_game_init();
                break;
            }
            case GameInitAction.toggle_game_type: {
                /* Custom and mission only. Load has its own button now, and
                   leaving it in the cycle meant the icon at (60,16) reads
                   "LOAD" while actually switching back to New Game. */
                var _next_type = GameType.custom;
                if (game_type == GameType.custom) {
                    _next_type = GameType.mission;
                }
                set_game_type(_next_type);
                break;
            }
            case GameInitAction.show_load: {
                if (game_type != GameType.load) {
                    set_game_type(GameType.load);
                    file_list.update();
                    load_status = L("Pick a save, then LOAD");
                    set_redraw();
                    break;
                }
                /* Already listing saves: this press loads the highlighted one,
                   so LOAD works on its own rather than needing START after. */
                load_selected_save();
                break;
            }
            case GameInitAction.show_netplay: {
                /* A toggle, so the same button is the way in and the way out.
                   EXIT cannot be the way out - it quits the game - so without
                   this the panel is a room with no door. */
                if (game_type == GameType.netplay) {
                    set_game_type(netplay_return_type);
                    set_redraw();
                    break;
                }
                netplay_return_type = game_type;
                set_game_type(GameType.netplay);
                set_redraw();
                break;
            }
            case GameInitAction.netplay_add: {
                /* Borrows the same typed-address prompt F8 uses, in its "add"
                   mode: this files the address in the list rather than dialling
                   it, because picking it is a separate decision. */
                global.net_ip_prompt = true;
                global.net_ip_prompt_mode = "add";
                keyboard_string = "";
                global.net_ip_text = "";
                net_set_status("");
                break;
            }
            case GameInitAction.netplay_host: {
                net_lobby_host();
                set_redraw();
                break;
            }
            case GameInitAction.netplay_mode_mission: {
                if (global.net_role == NetRole.host) {
                    netplay_custom = false;
                    set_redraw();
                }
                break;
            }
            case GameInitAction.netplay_mode_custom: {
                if (global.net_role == NetRole.host) {
                    netplay_custom = true;
                    set_redraw();
                }
                break;
            }
            case GameInitAction.netplay_new_map: {
                /* Only on a custom map: on the mission row this slot is the
                   "(done)" mark, which is not a button. */
                if (global.net_role == NetRole.host && netplay_custom) {
                    netplay_seed = game_init_random_default();
                    set_redraw();
                }
                break;
            }
            case GameInitAction.open_update: {
                /* Only while the note is actually drawn - the band is in the
                   clickmap whether or not there is anything on it. */
                if (update_note_shown()) {
                    show_debug_message("update: opening " + UPDATE_PAGE_URL);
                    url_open(UPDATE_PAGE_URL);
                }
                break;
            }
            case GameInitAction.toggle_language: {
                /* The name is only drawn when the version row is; the
                   generation label sits there otherwise. */
                if (!gen_active) {
                    locale_toggle();
                    set_redraw();
                }
                break;
            }
            case GameInitAction.show_options: {
                if (interface != undefined) {
                    interface.open_popup(PopupType.options);
                }
                break;
            }
            case GameInitAction.increment:
                /* On NET PLAY these are the host's mission arrows and nothing
                   else - they are drawn only then, so they should not quietly
                   change a hidden value the rest of the time. */
                if (game_type == GameType.netplay) {
                    if (global.net_role == NetRole.host) {
                        if (netplay_custom) {
                            netplay_size = min(netplay_size + 1, NET_CUSTOM_SIZE_MAX);
                        } else {
                            game_mission = min(game_mission + 1,
                                               game_info_get_mission_count() - 1);
                            mission = game_info_get_mission(game_mission);
                        }
                        set_redraw();
                    }
                    break;
                }
                switch (game_type) {
                    case GameType.mission:
                        game_mission = min(game_mission + 1, game_info_get_mission_count() - 1);
                        mission = game_info_get_mission(game_mission);
                        break;
                    case GameType.custom:
                        custom_mission.set_map_size(min(10, custom_mission.get_map_size() + 1));
                        break;
                }
                generate_map_preview();
                break;
            case GameInitAction.decrement:
                if (game_type == GameType.netplay) {
                    if (global.net_role == NetRole.host) {
                        if (netplay_custom) {
                            netplay_size = max(netplay_size - 1, NET_CUSTOM_SIZE_MIN);
                        } else {
                            game_mission = max(0, game_mission - 1);
                            mission = game_info_get_mission(game_mission);
                        }
                        set_redraw();
                    }
                    break;
                }
                switch (game_type) {
                    case GameType.mission:
                        game_mission = max(0, game_mission - 1);
                        mission = game_info_get_mission(game_mission);
                        break;
                    case GameType.custom:
                        custom_mission.set_map_size(max(3, custom_mission.get_map_size() - 1));
                        break;
                }
                generate_map_preview();
                break;
            case GameInitAction.close:
                /* On NET PLAY, EXIT is the way back to the screen this was
                   opened from. Quitting the whole game from a panel you stepped
                   into would be a nasty surprise. */
                if (game_type == GameType.netplay) {
                    set_game_type(netplay_return_type);
                    set_redraw();
                    break;
                }
                net_lobby_close();
                /* Quitting in-game returns here, so this is the way out. */
                game_end();
                break;
            case GameInitAction.gen_random: {
                random_input.set_random(game_init_random_default());
                set_redraw();
                break;
            }
            case GameInitAction.apply_random: {
                var _str = random_input.get_text();
                if (string_length(_str) == 16) {
                    apply_random(random_input.get_random());
                }
                break;
            }
            default:
                break;
        }
    };

    /// Dump what the save slots actually look like on disk. Bound to F12.
    static dump_save_state = function() {
        show_debug_message("--- savegame state ---");
        show_debug_message("game_type = " + string(game_type) +
                           " (load is " + string(GameType.load) + ")");
        show_debug_message("file_list displayed = " + string(file_list.is_displayed()) +
                           ", selected slot = " + string(file_list.get_selected_slot()));
        for (var _i = 0; _i < SAVEGAME_SLOTS; _i++) {
            var _path = savegame_slot_path(_i);
            show_debug_message("  slot " + string(_i) + ": " + _path +
                               " exists=" + string(file_exists(_path)) +
                               " label=" + savegame_slot_label(_i));
        }
        show_debug_message("last load error: '" + savegame_last_error() + "'");
        show_debug_message("--- end ---");
    };

    static handle_click_left = function(_cx, _cy) {
        var _clickmap = undefined;
        switch (game_type) {
            case GameType.mission:
                _clickmap = global.game_init_clickmap_mission;
                break;
            case GameType.custom:
                _clickmap = global.game_init_clickmap_custom;
                break;
            case GameType.load:
                _clickmap = global.game_init_clickmap_load;
                break;
            case GameType.netplay:
                _clickmap = global.game_init_clickmap_netplay;
                if (global.net_role == NetRole.host) {
                    _clickmap = global.game_init_clickmap_netplay_host;
                } else if (global.net_role == NetRole.client) {
                    _clickmap = global.game_init_clickmap_netplay_client;
                }
                break;
            default:
                return false;
        }

        var _i = 0;
        while (_clickmap[_i] >= 0) {
            if (_cx >= _clickmap[_i + 1] && _cx < _clickmap[_i + 1] + _clickmap[_i + 3] &&
                _cy >= _clickmap[_i + 2] && _cy < _clickmap[_i + 2] + _clickmap[_i + 4]) {
                set_redraw();
                handle_action(_clickmap[_i]);
                return true;
            }
            _i += 5;
        }

        /* The peer rows are not in the clickmap because there is no fixed
           number of them. Picking one dials it: if it answers, it is the host
           and we are the client. */
        if (game_type == GameType.netplay && !net_is_active()) {
            var _row = (_cy - NETPLAY_ROW_Y) div NETPLAY_ROW_H;
            if (_cy >= NETPLAY_ROW_Y && _row >= 0 &&
                _row < min(net_peer_count(), NETPLAY_ROW_MAX) &&
                _cx >= NETPLAY_ROW_X && _cx < NETPLAY_ROW_X + 300) {
                var _peer = net_peer_at(_row);
                if (_peer != undefined) {
                    set_redraw();
                    /* A pc we can hear that is not hosting is not joinable,
                       and dialling it would only fail two seconds later with
                       a message about ports. Say the useful thing instead. */
                    if (net_peer_is_live(_peer) && _peer.hosting != NET_HOSTING_OPEN) {
                        if (_peer.hosting == NET_HOSTING_FULL) {
                            net_set_status(LF("{0} already has a player 2",
                                              net_peer_label(_peer)));
                        } else {
                            net_set_status(LF("{0} is not hosting - on that pc,"
                                              + " CLICK HOST first",
                                              net_peer_label(_peer)));
                        }
                        return true;
                    }
                    net_lobby_pick(_peer.ip);
                }
                return true;
            }
        }

        /* Check player area */
        var _lx = 0;
        var _ly = 0;
        for (var _p = 0; _p < GAME_MAX_PLAYER_COUNT; _p++) {
            var _px = 20 + _lx * 80;
            var _py = 56 + _ly * 80;
            if ((_cx > _px) && (_cx < _px + 80) && (_cy > _py) && (_cy < _py + 80)) {
                if (handle_player_click(_p, _cx - _px, _cy - _py)) {
                    break;
                }
            }
            _lx++;
            if (_p == 1) {
                _ly++;
                _lx = 0;
            }
        }

        return true;
    };

    static get_next_character = function(_player_index) {
        var _in_use = false;
        var _player = mission.get_player(_player_index);
        var _next = _player.get_face();
        do {
            _next = (_next + 1) mod 14;
            _next = max(1, _next);
            /* Check that face is not already in use by another player */
            _in_use = false;
            var _count = mission.get_player_count();
            for (var _i = 0; _i < _count; _i++) {
                if (_player_index != _i && mission.get_player(_i).get_face() == _next) {
                    _in_use = true;
                    break;
                }
            }
        } until (!_in_use);

        return _next;
    };

    static handle_player_click = function(_player_index, _cx, _cy) {
        if (game_type != GameType.custom) {
            return true;
        }

        if (_cx < 8 || _cx > 8 + 64 || _cy < 8 || _cy > 76) {
            return false;
        }

        if ((_cx < 8 + 32) && (_cy < 72)) {
            if (_player_index >= mission.get_player_count()) {
                return true;
            }
            var _player = mission.get_player(_player_index);
            _player.set_character(get_next_character(_player_index));
        } else if ((_cx > 16 + 32) && (_cy < 24)) {
            if (_player_index >= mission.get_player_count()) {
                mission.add_player(0, { red: 0, green: 0, blue: 0 }, 20, 20, 20);
                _player_index = mission.get_player_count() - 1;
                var _player = mission.get_player(_player_index);
                _player.set_character(get_next_character(_player_index));
            } else {
                if (_player_index > 0) {
                    mission.remove_player(_player_index);
                }
            }
        } else {
            if (_player_index >= mission.get_player_count()) {
                return true;
            }
            var _player = mission.get_player(_player_index);
            _cx -= 8 + 32 + 8 + 3;
            if (_cx < 0) {
                return false;
            }
            if (_cy >= 27 && _cy < 69) {
                var _value = clamp(68 - _cy, 0, 40);
                if (_cx > 0 && _cx < 6) {
                    /* Supplies */
                    _player.set_supplies(_value);
                } else if (_cx > 6 && _cx < 12) {
                    /* Intelligence */
                    _player.set_intelligence(_value);
                } else if (_cx > 12 && _cx < 18) {
                    /* Reproduction */
                    _player.set_reproduction(_value);
                }
            }
        }

        set_redraw();

        return true;
    };

    /// Start generating the preview. The work itself happens a phase at a time
    /// in step_map_preview, called once per frame from obj_game's Step.
    ///
    /// GameMaker is single threaded, so the old version - which generated the
    /// whole map here and then set the minimap - could not show progress even
    /// in principle: nothing draws until the event returns, so the game just
    /// stopped for as long as it took. Above map size 5 that is long enough to
    /// look like a hang.
    ///
    /// Nothing about the map changes. The generator walks the same phase list
    /// in the same order from the same random stream whether it is stepped or
    /// run in one go - see ClassicMapGenerator.generate_step.
    static generate_map_preview = function() {
        /* Nothing that feeds the map has changed, so the map cannot change
           either - don't spend half a minute arriving back where we started.
           This is what stops the size arrow regenerating when it is already at
           10 (or 3) and the click changes nothing, and it makes a stray
           re-trigger from anywhere else harmless too. */
        var _size = mission.get_map_size();
        var _seed = random_state_to_string(mission.get_random_base());
        if (map != undefined && !gen_active &&
            _size == gen_done_size && _seed == gen_done_seed &&
            game_type == gen_done_type) {
            return;
        }

        gen_want_size = _size;
        gen_want_seed = _seed;
        gen_want_type = game_type;

        gen_map = new Map(new MapGeometry(_size));

        if (game_type == GameType.mission) {
            gen_generator = new ClassicMissionMapGenerator(gen_map,
                                                           mission.get_random_base());
            gen_generator.init();
        } else {
            gen_generator = new ClassicMapGenerator(gen_map,
                                                    mission.get_random_base());
            gen_generator.init(HeightGenerator.midpoints, true);
        }

        gen_generator.generate_begin();
        gen_times = array_create(gen_generator.gen_phase_count(), 0);
        gen_active = true;

        set_redraw();
    };

    /// One phase per frame. Returns true while there is still work to do.
    ///
    /// Starting a new preview while one is running simply throws the old one
    /// away - generate_map_preview replaces gen_generator outright - so
    /// holding the map size arrow down cannot leave a half-built map behind or
    /// stack up work.
    static step_map_preview = function() {
        if (!gen_active) {
            return false;
        }

        /* Time each phase. Now that generation is stepped, the cost of every
           phase can be measured on the machine that is actually slow rather
           than guessed at from reading the code - which is the only way to
           know what is worth optimising next. One line per generation, at the
           end, so it costs nothing to leave on. */
        var _t0 = get_timer();
        var _phase = gen_generator.gen_phase;
        var _done = gen_generator.generate_step();
        gen_times[_phase] = (get_timer() - _t0) / 1000;   /* ms */

        set_redraw();

        if (!_done) {
            return true;
        }

        var _t1 = get_timer();
        gen_map.init_tiles(gen_generator);
        var _tiles_ms = (get_timer() - _t1) / 1000;

        gen_done_size = gen_want_size;
        gen_done_seed = gen_want_seed;
        gen_done_type = gen_want_type;

        var _total = _tiles_ms;
        var _line = "";
        for (var _i = 0; _i < array_length(gen_times); _i++) {
            _total += gen_times[_i];
            _line += " " + string(_i) + ":" + string(round(gen_times[_i]));
        }
        show_debug_message("mapgen: size " + string(mission.get_map_size()) +
                           " took " + string(round(_total)) + "ms" +
                           " (per phase, ms:" + _line +
                           ", init_tiles:" + string(round(_tiles_ms)) + ")");

        map = gen_map;
        minimap.set_map(map);

        gen_active = false;
        gen_generator = undefined;
        gen_map = undefined;
        return false;
    };

    /// "GENERATING - <phase>" and a bar, along the bottom of the panel, to the
    /// left of the NET PLAY and LOAD buttons. Drawn only while a preview is
    /// being built.
    static draw_map_progress = function() {
        if (!gen_active) {
            return;
        }

        var _total = gen_generator.gen_phase_count();
        var _done = gen_generator.gen_phase;
        if (_done > _total) {
            _done = _total;
        }

        /* "MAP" dropped from the label and the whole thing cut to the row's
           width: the bottom row carries NET PLAY and LOAD now, and the longest
           phase name at the old wording ran 32 characters, straight across
           them. */
        var _label = L("GENERATING - ") + L(gen_generator.gen_phase_name());
        if (string_length(_label) > GEN_LABEL_COLS) {
            _label = string_copy(_label, 1, GEN_LABEL_COLS);
        }
        gfx_draw_string(GEN_BAR_X, GEN_BAR_LABEL_Y, _label,
                        make_colour_rgb(0xff, 0xff, 0xff), -1);

        /* Frame, then the filled part. Drawn with rectangles rather than a row
           of dashes because the game font has no character that fills its cell,
           so a text bar would be a dotted line. */
        gfx_draw_rect(GEN_BAR_X, GEN_BAR_Y, GEN_BAR_W, GEN_BAR_H,
                      make_colour_rgb(0x00, 0x00, 0x00));

        var _fill = ((GEN_BAR_W - 2) * _done) div _total;
        if (_fill > 0) {
            gfx_fill_rect(GEN_BAR_X + 1, GEN_BAR_Y + 1, _fill, GEN_BAR_H - 2,
                          make_colour_rgb(0x00, 0xe3, 0xe3));
        }
    };

    /// Regenerates the preview for the current mission settings.
    static update_map = function() {
        generate_map_preview();
    };

    // Constructor body: GameInitBox(Interface *interface)
    set_size(360, 254);

    load_status = "";

    /* Map generation in progress, stepped a phase at a time from obj_game's
       Step so the panel can draw a bar. See generate_map_preview. */
    gen_active = false;
    gen_generator = undefined;
    gen_map = undefined;
    gen_times = [];

    /* What the map on screen was built from, and what the run in progress is
       building. -1 / "" means "nothing yet", so the first call always
       generates. See generate_map_preview. */
    gen_done_size = -1;
    gen_done_seed = "";
    gen_done_type = -1;
    gen_want_size = -1;
    gen_want_seed = "";
    gen_want_type = -1;

    custom_mission = new GameInfo(game_init_random_default());
    custom_mission.remove_all_players();
    custom_mission.add_player(12, { red: 0x00, green: 0xe3, blue: 0xe3 }, 40, 40, 40);
    custom_mission.add_player(1, { red: 0xcf, green: 0x63, blue: 0x63 }, 20, 30, 40);
    mission = custom_mission;

    minimap.set_displayed(true);
    minimap.set_size(150, 160);
    add_float(minimap, 190, 55);

    generate_map_preview();

    random_input.set_random(custom_mission.get_random_base());
    random_input.set_displayed(true);
    add_float(random_input, 19 + 31 * 8, 15);

    file_list.set_size(160, 160);
    file_list.set_displayed(false);
    /* Clicking a save loads it straight away. Previewing first meant reading
       the whole file only to read it again on LOAD, and it was not obvious that
       a second button press was needed. */
    file_list.set_selection_handler(method(self, function(_item) {
        load_selected_save();
    }));
    add_float(file_list, 20, 55);
}
