// scr_game_init.gml - Ported from Freeserf src/game-init.h / src/game-init.cc
// (GPL-3.0), original copyright (C) 2013-2018 Jon Lund Steffensen
// <jonlst@gmail.com>. Game initialization GUI component (the "new game" box)
// and the RandomInput text widget.
//
// freeserf is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Differences from the C++:
//  - There is no GameManager: ActionStartGame creates `new Game()`, runs
//    `mission.instantiate(game)` (scr_mission.gml) and hands the game to
//    `interface.on_new_game(game)`.
//  - Save/load (GameStore / GameManager::load_game) is not ported: the
//    GameLoad game type shows the (stub) ListSavedFiles but starting it does
//    nothing.
//  - RandomInput is a self-contained GuiObject here (it carries the parts of
//    TextInput it needs: text, max_length, filter, focus drawing, key input).
//    NOTE: scr_popup.gml currently contains a STUB `RandomInput` constructor
//    (lines ~2215-2228) that must be removed when this file is added.
//  - FREESERF_VERSION (generated by the build) is the GAME_INIT_VERSION macro.

#macro GAME_INIT_VERSION "SettlersGM"

// ---------------------------------------------------------------------------
// Version, and the update check behind the line at the bottom of the start
// screen.
//
// The running build's version is GM_version, which is the string set in Game
// Options for the target platform - so bumping the version is done in the IDE
// where it belongs, and nothing here has to be kept in step with it by hand.
//
// The latest available version is one line of text in the repository, fetched
// over HTTP at startup. A plain text file rather than JSON on purpose: there is
// nothing to parse, nothing to go wrong with a struct that turned out not to
// have the field, and it is one keystroke to edit. Only the FIRST line is read,
// so notes, a download URL or anything else can be added underneath later
// without breaking a build that is already out in the world.
// ---------------------------------------------------------------------------

#macro UPDATE_CHECK_URL "https://raw.githubusercontent.com/RobertRamsay/SettlersGM/main/version.txt"

/// The version this build reports, from Game Options.
function game_version() {
    return string(GM_version);
}

/// Everything the update check owns, laid out before anything can read it.
/// Called from obj_game Create.
function update_check_init() {
    global.update_request_id = -1;
    global.update_latest = "";
    global.update_available = false;
    global.update_checked = false;
}

/// Fire the request. Nothing waits on it: the answer turns up in obj_game's
/// Async HTTP event whenever it turns up, and if it never does - no network, a
/// proxy, GitHub having a bad day - the start screen simply never grows the
/// extra word. An update check is not allowed to be a reason the game does not
/// start.
function update_check_start() {
    update_check_init();
    global.update_request_id = http_get(UPDATE_CHECK_URL);
}

/// First line of a fetched file, without its line ending or surrounding space.
function update_first_line(_text) {
    var _s = string(_text);
    var _cut = string_length(_s);

    var _nl = string_pos("\n", _s);
    if (_nl > 0) {
        _cut = _nl - 1;
    }
    var _cr = string_pos("\r", _s);
    if (_cr > 0 && _cr - 1 < _cut) {
        _cut = _cr - 1;
    }

    return string_trim(string_copy(_s, 1, _cut));
}

/// Is this a version and nothing else? Digits and dots, at least one digit, and
/// short enough to be one. Anything else - a 404 page, a login redirect, an
/// error from a captive portal - is thrown away rather than displayed.
function update_looks_like_version(_str) {
    var _n = string_length(_str);
    if (_n < 1 || _n > 24) {
        return false;
    }

    /* string_pos against a set of characters rather than `_c >= "0"`: the
       relational operators are for numbers, and what GML does with them on two
       strings is not something worth finding out at a customer's machine. */
    var _digits = 0;
    for (var _i = 1; _i <= _n; _i++) {
        var _c = string_char_at(_str, _i);
        if (_c == ".") {
            continue;
        }
        if (string_pos(_c, "0123456789") == 0) {
            return false;
        }
        _digits += 1;
    }

    return (_digits > 0);
}

/// The _index'th dot-separated number of a version string, or 0 past the end.
/// Hand-rolled rather than string_split so that a version with any number of
/// parts compares against one with any other: "1.2" and "1.2.0.0" are equal.
function update_version_part(_str, _index) {
    var _from = 1;
    var _n = string_length(_str);
    var _part = 0;

    while (_part <= _index) {
        var _to = _from;
        while (_to <= _n && string_char_at(_str, _to) != ".") {
            _to += 1;
        }
        if (_part == _index) {
            if (_to == _from) {
                return 0;
            }
            return real(string_copy(_str, _from, _to - _from));
        }
        if (_to > _n) {
            return 0;
        }
        _from = _to + 1;
        _part += 1;
    }

    return 0;
}

/// Is _latest newer than _current? Compared number by number, never as strings,
/// because "1.0.10.0" sorts BEFORE "1.0.9.0" alphabetically and that would
/// announce an update that is really a downgrade.
function update_version_is_newer(_latest, _current) {
    for (var _i = 0; _i < 6; _i++) {
        var _l = update_version_part(_latest, _i);
        var _c = update_version_part(_current, _i);
        if (_l > _c) {
            return true;
        }
        if (_l < _c) {
            return false;
        }
    }

    return false;
}

/// obj_game's Async HTTP event hands the map straight here.
function update_check_handle_async(_async) {
    if (global.update_request_id < 0) {
        return;
    }
    if (_async[? "id"] != global.update_request_id) {
        return;
    }

    var _status = _async[? "status"];
    if (_status == 1) {
        /* Still downloading. */
        return;
    }

    global.update_request_id = -1;
    global.update_checked = true;

    if (_status != 0) {
        show_debug_message("update: check failed, status " + string(_status));
        return;
    }
    if (_async[? "http_status"] != 200) {
        show_debug_message("update: check got HTTP " + string(_async[? "http_status"]));
        return;
    }

    var _latest = update_first_line(_async[? "result"]);
    if (!update_looks_like_version(_latest)) {
        show_debug_message("update: ignoring unrecognised version file");
        return;
    }

    global.update_latest = _latest;
    global.update_available = update_version_is_newer(_latest, game_version());
    show_debug_message("update: running " + game_version() + ", latest " + _latest);
}

/// GameInitBox::Action
enum GameInitAction {
    start_game = 0,
    toggle_game_type,
    show_options,
    increment,
    decrement,
    close,
    gen_random,
    apply_random,
    show_load,
    show_netplay,
    netplay_add,
    netplay_forget
}

/// GameInitBox::GameType
enum GameType {
    custom = 0,
    mission = 1,
    load = 2,
    netplay = 3
}

function game_init_init_tables() {
    if (variable_global_exists("game_init_layout")) {
        return;
    }

    global.game_init_color_green = make_colour_rgb(0x73, 0xb3, 0x43);
    global.game_init_color_black = make_colour_rgb(0x00, 0x00, 0x00);
    global.game_init_color_supplies = make_colour_rgb(0x00, 0x93, 0x87);
    global.game_init_color_intelligence = make_colour_rgb(0x6b, 0xab, 0x3b);
    global.game_init_color_reproduction = make_colour_rgb(0xa7, 0x27, 0x27);

    // TextInput colours
    global.game_init_color_focus = make_colour_rgb(0x00, 0x8b, 0x47);

    // internal_draw: const int layout[]
    global.game_init_layout = [
        266, 0, 0,    // Start button
        267, 36, 0,   // Options button
        -1
    ];

    // draw_player_box: const int layout[]
    global.game_init_player_layout = [
        251, 0, 0,
        252, 0, 72,
        253, 0, 8,
        254, 5, 8,
        255, 9, 8,
        -1
    ];

    // handle_click_left clickmaps
    global.game_init_clickmap_mission = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_load,        292, 216, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.increment,        284,  16, 16, 16,
        GameInitAction.decrement,        284,  32, 16, 16,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];

    global.game_init_clickmap_custom = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_load,        292, 216, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.increment,        220,  24, 24, 24,
        GameInitAction.decrement,        220,  16,  8,  8,
        GameInitAction.gen_random,       244,  16, 16,  8,
        GameInitAction.apply_random,     244,  24, 16, 24,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];

    global.game_init_clickmap_load = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_load,        292, 216, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];

    /* NET PLAY. START and the mission arrows are here for the host, and simply
       do nothing for the client - which one you are is not known until somebody
       picks, so the panel cannot be laid out differently per role. */
    global.game_init_clickmap_netplay = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.show_netplay,     NETPLAY_BTN_X, NETPLAY_BTN_Y, 32, 32,
        GameInitAction.increment,        284,  16, 16, 16,
        GameInitAction.decrement,        284,  32, 16, 16,
        GameInitAction.netplay_add,      NETPLAY_ADD_X, NETPLAY_ADD_Y, 150, 16,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];
}

/* Rows of the peer list, in box coordinates. */
#macro NETPLAY_ROW_X      20
#macro NETPLAY_ROW_Y      72
#macro NETPLAY_ROW_H      14
#macro NETPLAY_ROW_MAX    8

/* The NET PLAY button: the last frame of spr_icon. */
#macro NETPLAY_ICON       318

/* Where the NET PLAY button sits: the gap on the top row between the map size
   and the dice. The bottom-right slot it was in first is the wrong home for the
   only route into the panel, and it is crowded there. MISSION keeps its arrows
   at x 284 and CUSTOM its dice at 220, so 188 to 220 is the one 32-wide slot
   free on every screen. Move it by changing these two. */
#macro NETPLAY_BTN_X      188
#macro NETPLAY_BTN_Y      16

/* ADD AN ADDRESS, below the list. Its own row rather than the bottom-right
   slot, which is where LOAD is drawn - a button that reads LOAD and adds an
   address is worse than no button. */
#macro NETPLAY_ADD_X      20
#macro NETPLAY_ADD_Y      196

/// Port of Random::Random() (random.cc lines 27-33): seed from the clock
/// and consume one value.
function game_init_random_default() {
    var _rnd = new RandomState(irandom(0xFFFF), irandom(0xFFFF), irandom(0xFFFF));
    _rnd.next_random();
    return _rnd;
}

/// RandomInput : TextInput : GuiObject  (game-init.cc lines 36-83 plus the
/// parts of TextInput (text-input.cc) it relies on).
function RandomInput() : GuiObject() constructor {
    game_init_init_tables();

    // TextInput members
    text = "";
    max_length = 0;
    filter = undefined;
    draw_focus = true;
    color_focus = global.game_init_color_focus;
    color_text = global.game_init_color_green;
    color_background = global.game_init_color_black;

    // RandomInput members
    saved_text = "";

    // ------------------------------------------------------------ TextInput

    static set_text = function(_text) {
        text = _text;
        set_redraw();
    };

    static get_text = function() {
        return text;
    };

    static set_max_length = function(_max_len) {
        max_length = _max_len;
        if (max_length != 0) {
            if (string_length(text) > max_length) {
                text = string_copy(text, 1, max_length);
            }
        }
    };

    static set_filter = function(_filter) {
        filter = _filter;
    };

    /// The NET PLAY panel.
    ///
    /// Everyone listed here is a potential host, including us. Picking one dials
    /// it and makes us the client; if they pick us first we become the host
    /// instead. Nothing here declares a role in advance, because until somebody
    /// moves there is no role to declare.
    static draw_netplay = function() {
        var _white = make_colour_rgb(0xff, 0xff, 0xff);
        var _grey  = make_colour_rgb(0x90, 0x90, 0x90);
        var _amber = make_colour_rgb(0xff, 0xff, 0x99);

        draw_box_string(10, 2, "Net play");

        if (net_is_running()) {
            /* In a game already - the panel is just a status board now. */
            gfx_draw_string(NETPLAY_ROW_X, 56, "In a game. " + net_status_line(),
                            _amber, -1);
            return;
        }

        if (net_is_active()) {
            var _role = "connected";
            if (global.net_role == NetRole.host) {
                _role = "YOU ARE THE HOST - pick a mission and press START";
            } else {
                _role = "connected - waiting for the host to start";
            }
            gfx_draw_string(NETPLAY_ROW_X, 56, _role, _amber, -1);

            if (global.net_role == NetRole.host) {
                draw_box_string(10, 18, "Mission:");
                draw_box_string(20, 18, string(game_mission + 1));
                draw_box_icon(33, 0, 237);   // Up
                draw_box_icon(33, 16, 240);  // Down
            }
            return;
        }

        gfx_draw_string(NETPLAY_ROW_X, 56, "Pick a machine to play against:",
                        _white, -1);

        var _count = net_peer_count();
        if (_count == 0) {
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_ROW_Y,
                            "nobody yet - open NET PLAY on the other pc,", _grey, -1);
            gfx_draw_string(NETPLAY_ROW_X, NETPLAY_ROW_Y + NETPLAY_ROW_H,
                            "or ADD an address if it is not on this network",
                            _grey, -1);
        }

        var _rows = min(_count, NETPLAY_ROW_MAX);
        for (var _i = 0; _i < _rows; _i++) {
            var _peer = net_peer_at(_i);
            var _y = NETPLAY_ROW_Y + _i * NETPLAY_ROW_H;

            var _label = _peer.ip;
            if (_peer.name != "") {
                _label += "  (" + _peer.name + ")";
            }

            /* Live means it shouted within the last few seconds. A typed
               address that is not answering stays listed and says so, rather
               than disappearing while you are reading it. */
            var _colour = _grey;
            var _tail = "   no answer";
            if (net_peer_is_live(_peer)) {
                _colour = _white;
                _tail = "";
            }
            if (_peer.manual) {
                _tail += "   [added]";
            }

            gfx_draw_string(NETPLAY_ROW_X, _y, _label + _tail, _colour, -1);
        }

        gfx_draw_string(NETPLAY_ADD_X, NETPLAY_ADD_Y, "[ ADD AN ADDRESS ]",
                        _white, -1);

        if (net_status_line() != "") {
            gfx_draw_string(NETPLAY_ROW_X, 216, net_status_line(), _amber, -1);
        }
    };

    static internal_draw = function() {
        gfx_fill_rect(0, 0, width, height, color_background);
        if (draw_focus && focused) {
            gfx_draw_rect(0, 0, width, height, color_focus);
        }
        var _ch_width = width div 8;
        var _str = text;
        var _cx = 0;
        var _cy = 0;
        if (draw_focus) {
            _cx = 1;
            _cy = 1;
        }
        while (string_length(_str) > 0) {
            var _substr = string_copy(_str, 1, _ch_width);
            _str = string_delete(_str, 1, _ch_width);
            gfx_draw_string(_cx, _cy, _substr, color_text, -1);
            _cy += 8;
        }
    };

    /// TextInput::handle_key_pressed(char key, int modifier); _key is the
    /// ascii code (8 = backspace).
    static handle_key_pressed = function(_key, _modifier) {
        if (!focused) {
            return false;
        }

        if ((max_length != 0) && (string_length(text) >= max_length)) {
            return true;
        }

        if ((_key == 8) && (string_length(text) > 0)) {
            text = string_copy(text, 1, string_length(text) - 1);
            set_redraw();
            return true;
        }

        if (filter != undefined) {
            if (!filter(_key, self)) {
                return true;
            }
        }

        text += chr(_key);

        set_redraw();

        return true;
    };

    // ---------------------------------------------------------- RandomInput

    /// static bool text_input_filter(const char key, TextInput *text_input)
    static text_input_filter = function(_key, _text_input) {
        if (_key < ord("1") || _key > ord("8")) {
            return false;
        }

        if (string_length(_text_input.get_text()) > 16) {
            return false;
        }

        return true;
    };

    /// _rnd: RandomState
    static set_random = function(_rnd) {
        var _str = random_state_to_string(_rnd);
        set_text(_str);
    };

    /// Returns a RandomState built from the 16-character text.
    static get_random = function() {
        return random_state_from_string(text);
    };

    static handle_click_left = function(_cx, _cy) {
        // TextInput::handle_click_left(cx, cy)
        set_focused();
        saved_text = text;
        text = "";
        return true;
    };

    static handle_focus_loose = function() {
        // TextInput::handle_focus_loose()
        focused = false;
        set_redraw();
        if ((string_length(text) < 16) && (string_length(saved_text) == 16)) {
            text = saved_text;
            saved_text = "";
        }
        return true;
    };

    // Constructor body: RandomInput()
    set_filter(text_input_filter);
    set_size(34, 34);
    set_max_length(16);
}

/// GameInitBox : GuiObject  (C++: explicit GameInitBox(Interface *interface))
function GameInitBox(_interface) : GuiObject() constructor {
    game_init_init_tables();

    interface = _interface;

    game_type = GameType.custom;
    game_mission = 0;

    /* Which screen NET PLAY was opened from, so the same button goes back to
       it rather than always landing on one of them. */
    netplay_return_type = GameType.custom;

    custom_mission = undefined;
    mission = undefined;

    random_input = new RandomInput();
    map = undefined;
    minimap = new Minimap(undefined);
    file_list = new ListSavedFiles();

    static draw_box_icon = function(_ix, _iy, _sprite) {
        gfx_draw_sprite(8 * _ix + 20, _iy + 16, Asset.icon, _sprite);
    };

    static draw_box_string = function(_sx, _sy, _str) {
        gfx_draw_string(8 * _sx + 20, _sy + 16, _str,
                        global.game_init_color_green, global.game_init_color_black);
    };

    static draw_bg = function() {   // C++ draw_background (legacy GM built-in name)
        // Background
        var _icon = 290;
        for (var _by = 0; _by < height; _by += 8) {
            for (var _bx = 0; _bx < width; _bx += 40) {
                gfx_draw_sprite(_bx, _by, Asset.icon, _icon);
            }
            _icon--;
            if (_icon < 290) {
                _icon = 294;
            }
        }
    };

    /* Get the sprite number for a face. */
    static get_player_face_sprite = function(_face) {
        if (_face != 0) {
            return 0x10b + _face;
        }
        return 0x119; /* sprite_face_none */
    };

    static internal_draw = function() {
        draw_bg();

        /* Popup frame art rather than frame_top: plain planks with a cap at
           each end, no studs partway along, and only 8px thick. */
        gfx_draw_frame_box(0, 0, width, height);

        /* LOAD is a real button now - icon 316, the game's own 32x32 LOAD
           plaque - drawn beside EXIT from the layout below rather than as a
           white label painted on a black rectangle in the middle of the bottom
           row. That was scaffolding, and it was sitting on the only stretch of
           that row wide enough for the version caption. */

        /* Full label of the highlighted save, in one fixed place above the
           list so the rows stay short and the date does not jump about. */
        if (game_type == GameType.load) {
            var _sel = file_list.get_selected_slot();
            if (_sel >= 0 && savegame_slot_exists(_sel)) {
                gfx_draw_string(20, 44, savegame_slot_label(_sel),
                                make_colour_rgb(0xff, 0xff, 0xff), -1);
            }
        }

        /* Below the list, not under it: file_list is 160x160 at (20,55) and
           paints a black background over everything from y=55 to y=215, so a
           status drawn inside that range was never visible. */
        if (load_status != "") {
            gfx_draw_string(20, 240, load_status,
                            make_colour_rgb(0xff, 0xff, 0x99), -1);
        }

        var _layout = global.game_init_layout;
        var _i = 0;
        while (_layout[_i] >= 0) {
            draw_box_icon(_layout[_i + 1], _layout[_i + 2], _layout[_i]);
            _i += 3;
        }

        /* NET PLAY, beside LOAD and EXIT. Icon 318 is the last frame of
           spr_icon. On the panel itself the same button reads ADD, because
           that is the only thing left to press there. */
        gfx_draw_sprite(NETPLAY_BTN_X, NETPLAY_BTN_Y, Asset.icon, NETPLAY_ICON);

        if (game_type == GameType.netplay) {
            draw_netplay();
        }

        /* Game type settings */
        switch (game_type) {
            case GameType.mission: {
                draw_box_icon(5, 0, 260);  // Game type

                var _level = string(game_mission + 1);

                draw_box_string(10, 2, "Start mission");
                draw_box_string(10, 18, "Mission:");
                draw_box_string(20, 18, _level);

                /* Not in the original: mark a mission already won, so you can
                   step through the list and see where you got to rather than
                   having to remember. progress_mission_is_done reads a cached
                   array, so asking every frame costs nothing. */
                if (progress_mission_is_done(game_mission)) {
                    draw_box_string(24, 18, "Complete");
                }


                draw_box_icon(33, 0, 237);  // Up button
                draw_box_icon(33, 16, 240);  // Down button

                break;
            }
            case GameType.custom: {
                draw_box_icon(5, 0, 263);  // Game type

                var _str_map_size = string(mission.get_map_size());

                draw_box_string(10, 2, "New game");
                draw_box_string(10, 18, "Mapsize:");
                draw_box_string(18, 18, _str_map_size);

                draw_box_icon(25, 0, 265);

                break;
            }
            case GameType.load: {
                draw_box_icon(5, 0, 316);  // Game type

                draw_box_string(10, 2, "Load game");

                break;
            }
        }

        /* Game info */
        if (game_type != GameType.load) {
            var _bx = 0;
            var _by = 0;
            for (var _p = 0; _p < GAME_MAX_PLAYER_COUNT; _p++) {
                draw_player_box(_p, 10 * _bx, 40 + _by * 80);
                _bx++;
                if (_p == 1) {
                    _by++;
                    _bx = 0;
                }
            }
        }

        /* Display program name and version in caption */
        draw_box_string(0, 212, GAME_INIT_VERSION + " " + game_version());

        /* And, when the repository says there is a newer build than this one,
           a word about it on the same line. Right-aligned rather than placed at
           a fixed column, because the length depends on how many parts the new
           version number has.

           The room it has is the gap between the name on the left, which ends
           at x 164, and the LOAD button, which starts at x 292: columns 18 to
           32, fifteen characters, ending at x 284 so there is daylight either
           side. There is no second line to fall back on - the map preview comes
           down to y 215 and this caption is at y 228 - so a version number too
           long to fit drops the number and keeps the word rather than running
           under the button. "UPDATE" alone still says what it needs to; the
           number is on the download page either way. */
        if (global.update_available) {
            var _note = "UPDATE " + global.update_latest;
            if (string_length(_note) > 15) {
                _note = "UPDATE";
            }
            draw_box_string(33 - string_length(_note), 212, _note);
        }

        /* Bottom-row buttons. LOAD is 32x32 against EXIT's 16x16, so it is
           placed by its own top-left rather than sharing a row of icon
           columns: x 292..324 puts it hard against EXIT, and y 216..248 clears
           the map preview above it (which ends at 215). */
        if (game_type != GameType.netplay) {
            draw_box_icon(34, 200, 316); /* load */
        }
        draw_box_icon(38, 208, 60);  /* exit */
    };

    static draw_player_box = function(_player, _bx, _by) {
        var _layout = global.game_init_player_layout;
        var _i = 0;
        while (_layout[_i] >= 0) {
            draw_box_icon(_bx + _layout[_i + 1], _by + _layout[_i + 2], _layout[_i]);
            _i += 3;
        }

        _by += 8;
        _bx += 1;

        var _face = 0;
        if (_player < mission.get_player_count()) {
            _face = mission.get_player(_player).get_face();
        }

        draw_box_icon(_bx, _by, get_player_face_sprite(_face));
        draw_box_icon(_bx + 5, _by, 282);
        if (game_type == GameType.custom) {
            draw_box_icon(_bx + 4, _by, 308);
            if (_face == 0) {
                draw_box_icon(_bx + 5, _by, 287);
            } else {
                draw_box_icon(_bx + 5, _by, 259);
            }
        }

        if (_player < mission.get_player_count()) {
            _bx *= 8;

            var _pi = mission.get_player(_player);
            var _supplies = _pi.get_supplies();
            // (height 0 rects are skipped: gfx_fill_rect would draw a line)
            if (_supplies > 0) {
                gfx_fill_rect(_bx + 64, _by + 76 - _supplies, 4, _supplies,
                              global.game_init_color_supplies);
            }

            var _intelligence = _pi.get_intelligence();
            if (_intelligence > 0) {
                gfx_fill_rect(_bx + 70, _by + 76 - _intelligence, 4, _intelligence,
                              global.game_init_color_intelligence);
            }

            var _reproduction = _pi.get_reproduction();
            if (_reproduction > 0) {
                gfx_fill_rect(_bx + 76, _by + 76 - _reproduction, 4, _reproduction,
                              global.game_init_color_reproduction);
            }
        }
    };

    /// Switches to a game type (body of the inner switch of
    /// ActionToggleGameType).
    static set_game_type = function(_game_type) {
        game_type = _game_type;
        switch (game_type) {
            case GameType.mission: {
                mission = game_info_get_mission(game_mission);
                random_input.set_displayed(false);
                file_list.set_displayed(false);
                generate_map_preview();
                break;
            }
            case GameType.custom: {
                mission = custom_mission;
                random_input.set_displayed(true);
                random_input.set_random(custom_mission.get_random_base());
                file_list.set_displayed(false);
                generate_map_preview();
                break;
            }
            case GameType.load: {
                random_input.set_displayed(false);
                file_list.set_displayed(true);
                break;
            }
            case GameType.netplay: {
                random_input.set_displayed(false);
                file_list.set_displayed(false);
                /* The mission the host would start. Netplay uses the mission
                   list, so it needs a valid mission object the moment the panel
                   opens rather than the first time an arrow is pressed. */
                mission = game_info_get_mission(game_mission);
                net_lobby_open();
                break;
            }
        }

        /* Leaving the panel stops the shouting and closes the door, unless a
           game is already running on it. */
        if (game_type != GameType.netplay) {
            net_lobby_close();
        }
    };

    /// GameInitBox::apply_random(Random rnd) (declared in game-init.h; the
    /// body is what ActionApplyRandom does with a given random state).
    static apply_random = function(_rnd) {
        custom_mission.set_random_base(_rnd);
        mission = custom_mission;
        generate_map_preview();
    };

    /// Load whatever the list has highlighted. Failures are reported in the
    /// box rather than only to the debug log, which is easy to miss.
    static load_selected_save = function() {
        if (file_list.get_selected_slot() < 0) {
            load_status = "No save selected";
            set_redraw();
            return;
        }

        var _slot = file_list.get_selected_slot();
        var _path = file_list.get_selected();
        if (!file_exists(_path)) {
            load_status = "Slot " + string(_slot + 1) + " is empty";
            set_redraw();
            return;
        }

        var _loaded = game_store_load(_path);
        if (_loaded == undefined) {
            load_status = savegame_last_error();
            if (load_status == "") {
                load_status = "Save could not be read";
            }
            set_redraw();
            return;
        }

        var _loaded_map = _loaded.get_map();
        if (_loaded_map == undefined || !is_struct(_loaded_map) ||
            !variable_struct_exists(_loaded_map, "geom")) {
            load_status = "Save has no usable map";
            set_redraw();
            return;
        }

        if (interface == undefined) {
            return;
        }

        load_status = "Loading...";
        set_redraw();
        interface.request_game(_loaded);
    };

    static handle_action = function(_action) {
        switch (_action) {
            case GameInitAction.start_game: {
                if (game_type == GameType.netplay) {
                    /* Only the host starts, and only once somebody is actually
                       connected. The client's START does nothing at all, which
                       is correct: it has nothing to tell the other machine. */
                    if (global.net_role != NetRole.host || global.net_socket < 0) {
                        break;
                    }
                    net_lobby_close();
                    net_host_start_game(interface, game_mission);
                    interface.close_game_init();
                    break;
                }

                if (game_type == GameType.load) {
                    load_selected_save();
                    return;
                } else {
                    // GameManager::start_game(mission)
                    var _game = new Game();
                    if (mission.instantiate(_game) == undefined) {
                        return;
                    }
                    /* Remember which mission this is so winning it can tick it
                       off in the list. A custom game keeps the constructor's
                       -1, because there is no entry to tick. */
                    if (game_type == GameType.mission) {
                        _game.mission_index = game_mission;
                        show_debug_message("game init: starting mission " +
                                           string(game_mission + 1) +
                                           " (index " + string(game_mission) + ")");
                    }
                    /* Nothing records the current mission here: Interface.set_game
                       does it for every game that becomes current, this one
                       included. A custom game keeps the constructor's -1 and so
                       cannot tick a mission off. */
                    interface.on_new_game(_game);
                }

                interface.close_game_init();
                break;
            }
            case GameInitAction.toggle_game_type: {
                /* Custom and mission only. Load has its own button now, and
                   leaving it in the cycle meant the icon at (60,16) reads
                   "LOAD" while actually switching back to New Game. */
                var _next_type = GameType.custom;
                if (game_type == GameType.custom) {
                    _next_type = GameType.mission;
                }
                set_game_type(_next_type);
                break;
            }
            case GameInitAction.show_load: {
                if (game_type != GameType.load) {
                    set_game_type(GameType.load);
                    file_list.update();
                    load_status = "Pick a save, then LOAD";
                    set_redraw();
                    break;
                }
                /* Already listing saves: this press loads the highlighted one,
                   so LOAD works on its own rather than needing START after. */
                load_selected_save();
                break;
            }
            case GameInitAction.show_netplay: {
                /* A toggle, so the same button is the way in and the way out.
                   EXIT cannot be the way out - it quits the game - so without
                   this the panel is a room with no door. */
                if (game_type == GameType.netplay) {
                    set_game_type(netplay_return_type);
                    set_redraw();
                    break;
                }
                netplay_return_type = game_type;
                set_game_type(GameType.netplay);
                set_redraw();
                break;
            }
            case GameInitAction.netplay_add: {
                /* Borrows the same typed-address prompt F8 uses, in its "add"
                   mode: this files the address in the list rather than dialling
                   it, because picking it is a separate decision. */
                global.net_ip_prompt = true;
                global.net_ip_prompt_mode = "add";
                keyboard_string = "";
                global.net_ip_text = "";
                break;
            }
            case GameInitAction.netplay_forget: {
                break;
            }
            case GameInitAction.show_options: {
                if (interface != undefined) {
                    interface.open_popup(PopupType.options);
                }
                break;
            }
            case GameInitAction.increment:
                switch (game_type) {
                    case GameType.mission:
                        game_mission = min(game_mission + 1, game_info_get_mission_count() - 1);
                        mission = game_info_get_mission(game_mission);
                        break;
                    case GameType.custom:
                        custom_mission.set_map_size(min(10, custom_mission.get_map_size() + 1));
                        break;
                }
                generate_map_preview();
                break;
            case GameInitAction.decrement:
                switch (game_type) {
                    case GameType.mission:
                        game_mission = max(0, game_mission - 1);
                        mission = game_info_get_mission(game_mission);
                        break;
                    case GameType.custom:
                        custom_mission.set_map_size(max(3, custom_mission.get_map_size() - 1));
                        break;
                }
                generate_map_preview();
                break;
            case GameInitAction.close:
                net_lobby_close();
                /* Quitting in-game returns here, so this is the way out. */
                game_end();
                break;
            case GameInitAction.gen_random: {
                random_input.set_random(game_init_random_default());
                set_redraw();
                break;
            }
            case GameInitAction.apply_random: {
                var _str = random_input.get_text();
                if (string_length(_str) == 16) {
                    apply_random(random_input.get_random());
                }
                break;
            }
            default:
                break;
        }
    };

    /// Dump what the save slots actually look like on disk. Bound to F12.
    static dump_save_state = function() {
        show_debug_message("--- savegame state ---");
        show_debug_message("game_type = " + string(game_type) +
                           " (load is " + string(GameType.load) + ")");
        show_debug_message("file_list displayed = " + string(file_list.is_displayed()) +
                           ", selected slot = " + string(file_list.get_selected_slot()));
        for (var _i = 0; _i < SAVEGAME_SLOTS; _i++) {
            var _path = savegame_slot_path(_i);
            show_debug_message("  slot " + string(_i) + ": " + _path +
                               " exists=" + string(file_exists(_path)) +
                               " label=" + savegame_slot_label(_i));
        }
        show_debug_message("last load error: '" + savegame_last_error() + "'");
        show_debug_message("--- end ---");
    };

    static handle_click_left = function(_cx, _cy) {
        var _clickmap = undefined;
        switch (game_type) {
            case GameType.mission:
                _clickmap = global.game_init_clickmap_mission;
                break;
            case GameType.custom:
                _clickmap = global.game_init_clickmap_custom;
                break;
            case GameType.load:
                _clickmap = global.game_init_clickmap_load;
                break;
            case GameType.netplay:
                _clickmap = global.game_init_clickmap_netplay;
                break;
            default:
                return false;
        }

        var _i = 0;
        while (_clickmap[_i] >= 0) {
            if (_cx >= _clickmap[_i + 1] && _cx < _clickmap[_i + 1] + _clickmap[_i + 3] &&
                _cy >= _clickmap[_i + 2] && _cy < _clickmap[_i + 2] + _clickmap[_i + 4]) {
                set_redraw();
                handle_action(_clickmap[_i]);
                return true;
            }
            _i += 5;
        }

        /* The peer rows are not in the clickmap because there is no fixed
           number of them. Picking one dials it: if it answers, it is the host
           and we are the client. */
        if (game_type == GameType.netplay && !net_is_active()) {
            var _row = (_cy - NETPLAY_ROW_Y) div NETPLAY_ROW_H;
            if (_cy >= NETPLAY_ROW_Y && _row >= 0 &&
                _row < min(net_peer_count(), NETPLAY_ROW_MAX) &&
                _cx >= NETPLAY_ROW_X && _cx < NETPLAY_ROW_X + 300) {
                var _peer = net_peer_at(_row);
                if (_peer != undefined) {
                    set_redraw();
                    net_lobby_pick(_peer.ip);
                }
                return true;
            }
        }

        /* Check player area */
        var _lx = 0;
        var _ly = 0;
        for (var _p = 0; _p < GAME_MAX_PLAYER_COUNT; _p++) {
            var _px = 20 + _lx * 80;
            var _py = 56 + _ly * 80;
            if ((_cx > _px) && (_cx < _px + 80) && (_cy > _py) && (_cy < _py + 80)) {
                if (handle_player_click(_p, _cx - _px, _cy - _py)) {
                    break;
                }
            }
            _lx++;
            if (_p == 1) {
                _ly++;
                _lx = 0;
            }
        }

        return true;
    };

    static get_next_character = function(_player_index) {
        var _in_use = false;
        var _player = mission.get_player(_player_index);
        var _next = _player.get_face();
        do {
            _next = (_next + 1) mod 14;
            _next = max(1, _next);
            /* Check that face is not already in use by another player */
            _in_use = false;
            var _count = mission.get_player_count();
            for (var _i = 0; _i < _count; _i++) {
                if (_player_index != _i && mission.get_player(_i).get_face() == _next) {
                    _in_use = true;
                    break;
                }
            }
        } until (!_in_use);

        return _next;
    };

    static handle_player_click = function(_player_index, _cx, _cy) {
        if (game_type != GameType.custom) {
            return true;
        }

        if (_cx < 8 || _cx > 8 + 64 || _cy < 8 || _cy > 76) {
            return false;
        }

        if ((_cx < 8 + 32) && (_cy < 72)) {
            if (_player_index >= mission.get_player_count()) {
                return true;
            }
            var _player = mission.get_player(_player_index);
            _player.set_character(get_next_character(_player_index));
        } else if ((_cx > 16 + 32) && (_cy < 24)) {
            if (_player_index >= mission.get_player_count()) {
                mission.add_player(0, { red: 0, green: 0, blue: 0 }, 20, 20, 20);
                _player_index = mission.get_player_count() - 1;
                var _player = mission.get_player(_player_index);
                _player.set_character(get_next_character(_player_index));
            } else {
                if (_player_index > 0) {
                    mission.remove_player(_player_index);
                }
            }
        } else {
            if (_player_index >= mission.get_player_count()) {
                return true;
            }
            var _player = mission.get_player(_player_index);
            _cx -= 8 + 32 + 8 + 3;
            if (_cx < 0) {
                return false;
            }
            if (_cy >= 27 && _cy < 69) {
                var _value = clamp(68 - _cy, 0, 40);
                if (_cx > 0 && _cx < 6) {
                    /* Supplies */
                    _player.set_supplies(_value);
                } else if (_cx > 6 && _cx < 12) {
                    /* Intelligence */
                    _player.set_intelligence(_value);
                } else if (_cx > 12 && _cx < 18) {
                    /* Reproduction */
                    _player.set_reproduction(_value);
                }
            }
        }

        set_redraw();

        return true;
    };

    static generate_map_preview = function() {
        map = new Map(new MapGeometry(mission.get_map_size()));
        if (game_type == GameType.mission) {
            var _generator = new ClassicMissionMapGenerator(map, mission.get_random_base());
            _generator.init();
            _generator.generate();
            map.init_tiles(_generator);
        } else {
            var _generator = new ClassicMapGenerator(map, mission.get_random_base());
            _generator.init(HeightGenerator.midpoints, true);
            _generator.generate();
            map.init_tiles(_generator);
        }

        minimap.set_map(map);

        set_redraw();
    };

    /// Regenerates the preview for the current mission settings.
    static update_map = function() {
        generate_map_preview();
    };

    // Constructor body: GameInitBox(Interface *interface)
    set_size(360, 254);

    load_status = "";

    custom_mission = new GameInfo(game_init_random_default());
    custom_mission.remove_all_players();
    custom_mission.add_player(12, { red: 0x00, green: 0xe3, blue: 0xe3 }, 40, 40, 40);
    custom_mission.add_player(1, { red: 0xcf, green: 0x63, blue: 0x63 }, 20, 30, 40);
    mission = custom_mission;

    minimap.set_displayed(true);
    minimap.set_size(150, 160);
    add_float(minimap, 190, 55);

    generate_map_preview();

    random_input.set_random(custom_mission.get_random_base());
    random_input.set_displayed(true);
    add_float(random_input, 19 + 31 * 8, 15);

    file_list.set_size(160, 160);
    file_list.set_displayed(false);
    /* Clicking a save loads it straight away. Previewing first meant reading
       the whole file only to read it again on LOAD, and it was not obvious that
       a second button press was needed. */
    file_list.set_selection_handler(method(self, function(_item) {
        load_selected_save();
    }));
    add_float(file_list, 20, 55);
}
