// scr_game_init.gml - Ported from Freeserf src/game-init.h / src/game-init.cc
// (GPL-3.0), original copyright (C) 2013-2018 Jon Lund Steffensen
// <jonlst@gmail.com>. Game initialization GUI component (the "new game" box)
// and the RandomInput text widget.
//
// freeserf is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Differences from the C++:
//  - There is no GameManager: ActionStartGame creates `new Game()`, runs
//    `mission.instantiate(game)` (scr_mission.gml) and hands the game to
//    `interface.on_new_game(game)`.
//  - Save/load (GameStore / GameManager::load_game) is not ported: the
//    GameLoad game type shows the (stub) ListSavedFiles but starting it does
//    nothing.
//  - RandomInput is a self-contained GuiObject here (it carries the parts of
//    TextInput it needs: text, max_length, filter, focus drawing, key input).
//    NOTE: scr_popup.gml currently contains a STUB `RandomInput` constructor
//    (lines ~2215-2228) that must be removed when this file is added.
//  - FREESERF_VERSION (generated by the build) is the GAME_INIT_VERSION macro.

#macro GAME_INIT_VERSION "SettlersGM"

/// GameInitBox::Action
enum GameInitAction {
    start_game = 0,
    toggle_game_type,
    show_options,
    increment,
    decrement,
    close,
    gen_random,
    apply_random
}

/// GameInitBox::GameType
enum GameType {
    custom = 0,
    mission = 1,
    load = 2
}

function game_init_init_tables() {
    if (variable_global_exists("game_init_layout")) {
        return;
    }

    global.game_init_color_green = make_colour_rgb(0x73, 0xb3, 0x43);
    global.game_init_color_black = make_colour_rgb(0x00, 0x00, 0x00);
    global.game_init_color_supplies = make_colour_rgb(0x00, 0x93, 0x87);
    global.game_init_color_intelligence = make_colour_rgb(0x6b, 0xab, 0x3b);
    global.game_init_color_reproduction = make_colour_rgb(0xa7, 0x27, 0x27);

    // TextInput colours
    global.game_init_color_focus = make_colour_rgb(0x00, 0x8b, 0x47);

    // internal_draw: const int layout[]
    global.game_init_layout = [
        266, 0, 0,    // Start button
        267, 36, 0,   // Options button
        -1
    ];

    // draw_player_box: const int layout[]
    global.game_init_player_layout = [
        251, 0, 0,
        252, 0, 72,
        253, 0, 8,
        254, 5, 8,
        255, 9, 8,
        -1
    ];

    // handle_click_left clickmaps
    global.game_init_clickmap_mission = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.increment,        284,  16, 16, 16,
        GameInitAction.decrement,        284,  32, 16, 16,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];

    global.game_init_clickmap_custom = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.increment,        220,  24, 24, 24,
        GameInitAction.decrement,        220,  16,  8,  8,
        GameInitAction.gen_random,       244,  16, 16,  8,
        GameInitAction.apply_random,     244,  24, 16, 24,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];

    global.game_init_clickmap_load = [
        GameInitAction.start_game,        20,  16, 32, 32,
        GameInitAction.toggle_game_type,  60,  16, 32, 32,
        GameInitAction.show_options,     308,  16, 32, 32,
        GameInitAction.close,            324, 216, 16, 16,
        -1
    ];
}

/// Port of Random::Random() (random.cc lines 27-33): seed from the clock
/// and consume one value.
function game_init_random_default() {
    var _rnd = new RandomState(irandom(0xFFFF), irandom(0xFFFF), irandom(0xFFFF));
    _rnd.next_random();
    return _rnd;
}

/// RandomInput : TextInput : GuiObject  (game-init.cc lines 36-83 plus the
/// parts of TextInput (text-input.cc) it relies on).
function RandomInput() : GuiObject() constructor {
    game_init_init_tables();

    // TextInput members
    text = "";
    max_length = 0;
    filter = undefined;
    draw_focus = true;
    color_focus = global.game_init_color_focus;
    color_text = global.game_init_color_green;
    color_background = global.game_init_color_black;

    // RandomInput members
    saved_text = "";

    // ------------------------------------------------------------ TextInput

    static set_text = function(_text) {
        text = _text;
        set_redraw();
    };

    static get_text = function() {
        return text;
    };

    static set_max_length = function(_max_len) {
        max_length = _max_len;
        if (max_length != 0) {
            if (string_length(text) > max_length) {
                text = string_copy(text, 1, max_length);
            }
        }
    };

    static set_filter = function(_filter) {
        filter = _filter;
    };

    static internal_draw = function() {
        gfx_fill_rect(0, 0, width, height, color_background);
        if (draw_focus && focused) {
            gfx_draw_rect(0, 0, width, height, color_focus);
        }
        var _ch_width = width div 8;
        var _str = text;
        var _cx = 0;
        var _cy = 0;
        if (draw_focus) {
            _cx = 1;
            _cy = 1;
        }
        while (string_length(_str) > 0) {
            var _substr = string_copy(_str, 1, _ch_width);
            _str = string_delete(_str, 1, _ch_width);
            gfx_draw_string(_cx, _cy, _substr, color_text, -1);
            _cy += 8;
        }
    };

    /// TextInput::handle_key_pressed(char key, int modifier); _key is the
    /// ascii code (8 = backspace).
    static handle_key_pressed = function(_key, _modifier) {
        if (!focused) {
            return false;
        }

        if ((max_length != 0) && (string_length(text) >= max_length)) {
            return true;
        }

        if ((_key == 8) && (string_length(text) > 0)) {
            text = string_copy(text, 1, string_length(text) - 1);
            set_redraw();
            return true;
        }

        if (filter != undefined) {
            if (!filter(_key, self)) {
                return true;
            }
        }

        text += chr(_key);

        set_redraw();

        return true;
    };

    // ---------------------------------------------------------- RandomInput

    /// static bool text_input_filter(const char key, TextInput *text_input)
    static text_input_filter = function(_key, _text_input) {
        if (_key < ord("1") || _key > ord("8")) {
            return false;
        }

        if (string_length(_text_input.get_text()) > 16) {
            return false;
        }

        return true;
    };

    /// _rnd: RandomState
    static set_random = function(_rnd) {
        var _str = random_state_to_string(_rnd);
        set_text(_str);
    };

    /// Returns a RandomState built from the 16-character text.
    static get_random = function() {
        return random_state_from_string(text);
    };

    static handle_click_left = function(_cx, _cy) {
        // TextInput::handle_click_left(cx, cy)
        set_focused();
        saved_text = text;
        text = "";
        return true;
    };

    static handle_focus_loose = function() {
        // TextInput::handle_focus_loose()
        focused = false;
        set_redraw();
        if ((string_length(text) < 16) && (string_length(saved_text) == 16)) {
            text = saved_text;
            saved_text = "";
        }
        return true;
    };

    // Constructor body: RandomInput()
    set_filter(text_input_filter);
    set_size(34, 34);
    set_max_length(16);
}

/// GameInitBox : GuiObject  (C++: explicit GameInitBox(Interface *interface))
function GameInitBox(_interface) : GuiObject() constructor {
    game_init_init_tables();

    interface = _interface;

    game_type = GameType.custom;
    game_mission = 0;

    custom_mission = undefined;
    mission = undefined;

    random_input = new RandomInput();
    map = undefined;
    minimap = new Minimap(undefined);
    file_list = new ListSavedFiles();

    static draw_box_icon = function(_ix, _iy, _sprite) {
        gfx_draw_sprite(8 * _ix + 20, _iy + 16, Asset.icon, _sprite);
    };

    static draw_box_string = function(_sx, _sy, _str) {
        gfx_draw_string(8 * _sx + 20, _sy + 16, _str,
                        global.game_init_color_green, global.game_init_color_black);
    };

    static draw_bg = function() {   // C++ draw_background (legacy GM built-in name)
        // Background
        var _icon = 290;
        for (var _by = 0; _by < height; _by += 8) {
            for (var _bx = 0; _bx < width; _bx += 40) {
                gfx_draw_sprite(_bx, _by, Asset.icon, _icon);
            }
            _icon--;
            if (_icon < 290) {
                _icon = 294;
            }
        }
    };

    /* Get the sprite number for a face. */
    static get_player_face_sprite = function(_face) {
        if (_face != 0) {
            return 0x10b + _face;
        }
        return 0x119; /* sprite_face_none */
    };

    static internal_draw = function() {
        draw_bg();

        var _layout = global.game_init_layout;
        var _i = 0;
        while (_layout[_i] >= 0) {
            draw_box_icon(_layout[_i + 1], _layout[_i + 2], _layout[_i]);
            _i += 3;
        }

        /* Game type settings */
        switch (game_type) {
            case GameType.mission: {
                draw_box_icon(5, 0, 260);  // Game type

                var _level = string(game_mission + 1);

                draw_box_string(10, 2, "Start mission");
                draw_box_string(10, 18, "Mission:");
                draw_box_string(20, 18, _level);

                draw_box_icon(33, 0, 237);  // Up button
                draw_box_icon(33, 16, 240);  // Down button

                break;
            }
            case GameType.custom: {
                draw_box_icon(5, 0, 263);  // Game type

                var _str_map_size = string(mission.get_map_size());

                draw_box_string(10, 2, "New game");
                draw_box_string(10, 18, "Mapsize:");
                draw_box_string(18, 18, _str_map_size);

                draw_box_icon(25, 0, 265);

                break;
            }
            case GameType.load: {
                draw_box_icon(5, 0, 316);  // Game type

                draw_box_string(10, 2, "Load game");

                break;
            }
        }

        /* Game info */
        if (game_type != GameType.load) {
            var _bx = 0;
            var _by = 0;
            for (var _p = 0; _p < GAME_MAX_PLAYER_COUNT; _p++) {
                draw_player_box(_p, 10 * _bx, 40 + _by * 80);
                _bx++;
                if (_p == 1) {
                    _by++;
                    _bx = 0;
                }
            }
        }

        /* Display program name and version in caption */
        draw_box_string(0, 212, GAME_INIT_VERSION);

        draw_box_icon(38, 208, 60); /* exit */
    };

    static draw_player_box = function(_player, _bx, _by) {
        var _layout = global.game_init_player_layout;
        var _i = 0;
        while (_layout[_i] >= 0) {
            draw_box_icon(_bx + _layout[_i + 1], _by + _layout[_i + 2], _layout[_i]);
            _i += 3;
        }

        _by += 8;
        _bx += 1;

        var _face = 0;
        if (_player < mission.get_player_count()) {
            _face = mission.get_player(_player).get_face();
        }

        draw_box_icon(_bx, _by, get_player_face_sprite(_face));
        draw_box_icon(_bx + 5, _by, 282);
        if (game_type == GameType.custom) {
            draw_box_icon(_bx + 4, _by, 308);
            if (_face == 0) {
                draw_box_icon(_bx + 5, _by, 287);
            } else {
                draw_box_icon(_bx + 5, _by, 259);
            }
        }

        if (_player < mission.get_player_count()) {
            _bx *= 8;

            var _pi = mission.get_player(_player);
            var _supplies = _pi.get_supplies();
            // (height 0 rects are skipped: gfx_fill_rect would draw a line)
            if (_supplies > 0) {
                gfx_fill_rect(_bx + 64, _by + 76 - _supplies, 4, _supplies,
                              global.game_init_color_supplies);
            }

            var _intelligence = _pi.get_intelligence();
            if (_intelligence > 0) {
                gfx_fill_rect(_bx + 70, _by + 76 - _intelligence, 4, _intelligence,
                              global.game_init_color_intelligence);
            }

            var _reproduction = _pi.get_reproduction();
            if (_reproduction > 0) {
                gfx_fill_rect(_bx + 76, _by + 76 - _reproduction, 4, _reproduction,
                              global.game_init_color_reproduction);
            }
        }
    };

    /// Switches to a game type (body of the inner switch of
    /// ActionToggleGameType).
    static set_game_type = function(_game_type) {
        game_type = _game_type;
        switch (game_type) {
            case GameType.mission: {
                mission = game_info_get_mission(game_mission);
                random_input.set_displayed(false);
                file_list.set_displayed(false);
                generate_map_preview();
                break;
            }
            case GameType.custom: {
                mission = custom_mission;
                random_input.set_displayed(true);
                random_input.set_random(custom_mission.get_random_base());
                file_list.set_displayed(false);
                generate_map_preview();
                break;
            }
            case GameType.load: {
                random_input.set_displayed(false);
                file_list.set_displayed(true);
                break;
            }
        }
    };

    /// GameInitBox::apply_random(Random rnd) (declared in game-init.h; the
    /// body is what ActionApplyRandom does with a given random state).
    static apply_random = function(_rnd) {
        custom_mission.set_random_base(_rnd);
        mission = custom_mission;
        generate_map_preview();
    };

    static handle_action = function(_action) {
        switch (_action) {
            case GameInitAction.start_game: {
                if (game_type == GameType.load) {
                    var _path = file_list.get_selected();
                    var _loaded = game_store_load(_path);
                    if (_loaded == undefined) {
                        show_debug_message("GameInitBox: could not load " + string(_path));
                        return;
                    }
                    if (interface != undefined) {
                        interface.set_game(_loaded);
                        interface.close_game_init();
                    }
                    return;
                } else {
                    // GameManager::start_game(mission)
                    var _game = new Game();
                    if (mission.instantiate(_game) == undefined) {
                        return;
                    }
                    interface.on_new_game(_game);
                }

                interface.close_game_init();
                break;
            }
            case GameInitAction.toggle_game_type: {
                var _next_type = game_type + 1;
                if (_next_type > GameType.load) {
                    _next_type = GameType.custom;
                }
                set_game_type(_next_type);
                break;
            }
            case GameInitAction.show_options: {
                if (interface != undefined) {
                    interface.open_popup(PopupType.options);
                }
                break;
            }
            case GameInitAction.increment:
                switch (game_type) {
                    case GameType.mission:
                        game_mission = min(game_mission + 1, game_info_get_mission_count() - 1);
                        mission = game_info_get_mission(game_mission);
                        break;
                    case GameType.custom:
                        custom_mission.set_map_size(min(10, custom_mission.get_map_size() + 1));
                        break;
                }
                generate_map_preview();
                break;
            case GameInitAction.decrement:
                switch (game_type) {
                    case GameType.mission:
                        game_mission = max(0, game_mission - 1);
                        mission = game_info_get_mission(game_mission);
                        break;
                    case GameType.custom:
                        custom_mission.set_map_size(max(3, custom_mission.get_map_size() - 1));
                        break;
                }
                generate_map_preview();
                break;
            case GameInitAction.close:
                interface.close_game_init();
                break;
            case GameInitAction.gen_random: {
                random_input.set_random(game_init_random_default());
                set_redraw();
                break;
            }
            case GameInitAction.apply_random: {
                var _str = random_input.get_text();
                if (string_length(_str) == 16) {
                    apply_random(random_input.get_random());
                }
                break;
            }
            default:
                break;
        }
    };

    static handle_click_left = function(_cx, _cy) {
        var _clickmap = undefined;
        switch (game_type) {
            case GameType.mission:
                _clickmap = global.game_init_clickmap_mission;
                break;
            case GameType.custom:
                _clickmap = global.game_init_clickmap_custom;
                break;
            case GameType.load:
                _clickmap = global.game_init_clickmap_load;
                break;
            default:
                return false;
        }

        var _i = 0;
        while (_clickmap[_i] >= 0) {
            if (_cx >= _clickmap[_i + 1] && _cx < _clickmap[_i + 1] + _clickmap[_i + 3] &&
                _cy >= _clickmap[_i + 2] && _cy < _clickmap[_i + 2] + _clickmap[_i + 4]) {
                set_redraw();
                handle_action(_clickmap[_i]);
                return true;
            }
            _i += 5;
        }

        /* Check player area */
        var _lx = 0;
        var _ly = 0;
        for (var _p = 0; _p < GAME_MAX_PLAYER_COUNT; _p++) {
            var _px = 20 + _lx * 80;
            var _py = 56 + _ly * 80;
            if ((_cx > _px) && (_cx < _px + 80) && (_cy > _py) && (_cy < _py + 80)) {
                if (handle_player_click(_p, _cx - _px, _cy - _py)) {
                    break;
                }
            }
            _lx++;
            if (_p == 1) {
                _ly++;
                _lx = 0;
            }
        }

        return true;
    };

    static get_next_character = function(_player_index) {
        var _in_use = false;
        var _player = mission.get_player(_player_index);
        var _next = _player.get_face();
        do {
            _next = (_next + 1) mod 14;
            _next = max(1, _next);
            /* Check that face is not already in use by another player */
            _in_use = false;
            var _count = mission.get_player_count();
            for (var _i = 0; _i < _count; _i++) {
                if (_player_index != _i && mission.get_player(_i).get_face() == _next) {
                    _in_use = true;
                    break;
                }
            }
        } until (!_in_use);

        return _next;
    };

    static handle_player_click = function(_player_index, _cx, _cy) {
        if (game_type != GameType.custom) {
            return true;
        }

        if (_cx < 8 || _cx > 8 + 64 || _cy < 8 || _cy > 76) {
            return false;
        }

        if ((_cx < 8 + 32) && (_cy < 72)) {
            if (_player_index >= mission.get_player_count()) {
                return true;
            }
            var _player = mission.get_player(_player_index);
            _player.set_character(get_next_character(_player_index));
        } else if ((_cx > 16 + 32) && (_cy < 24)) {
            if (_player_index >= mission.get_player_count()) {
                mission.add_player(0, { red: 0, green: 0, blue: 0 }, 20, 20, 20);
                _player_index = mission.get_player_count() - 1;
                var _player = mission.get_player(_player_index);
                _player.set_character(get_next_character(_player_index));
            } else {
                if (_player_index > 0) {
                    mission.remove_player(_player_index);
                }
            }
        } else {
            if (_player_index >= mission.get_player_count()) {
                return true;
            }
            var _player = mission.get_player(_player_index);
            _cx -= 8 + 32 + 8 + 3;
            if (_cx < 0) {
                return false;
            }
            if (_cy >= 27 && _cy < 69) {
                var _value = clamp(68 - _cy, 0, 40);
                if (_cx > 0 && _cx < 6) {
                    /* Supplies */
                    _player.set_supplies(_value);
                } else if (_cx > 6 && _cx < 12) {
                    /* Intelligence */
                    _player.set_intelligence(_value);
                } else if (_cx > 12 && _cx < 18) {
                    /* Reproduction */
                    _player.set_reproduction(_value);
                }
            }
        }

        set_redraw();

        return true;
    };

    static generate_map_preview = function() {
        map = new Map(new MapGeometry(mission.get_map_size()));
        if (game_type == GameType.mission) {
            var _generator = new ClassicMissionMapGenerator(map, mission.get_random_base());
            _generator.init();
            _generator.generate();
            map.init_tiles(_generator);
        } else {
            var _generator = new ClassicMapGenerator(map, mission.get_random_base());
            _generator.init(HeightGenerator.midpoints, true);
            _generator.generate();
            map.init_tiles(_generator);
        }

        minimap.set_map(map);

        set_redraw();
    };

    /// Regenerates the preview for the current mission settings.
    static update_map = function() {
        generate_map_preview();
    };

    // Constructor body: GameInitBox(Interface *interface)
    set_size(360, 254);

    custom_mission = new GameInfo(game_init_random_default());
    custom_mission.remove_all_players();
    custom_mission.add_player(12, { red: 0x00, green: 0xe3, blue: 0xe3 }, 40, 40, 40);
    custom_mission.add_player(1, { red: 0xcf, green: 0x63, blue: 0x63 }, 20, 30, 40);
    mission = custom_mission;

    minimap.set_displayed(true);
    minimap.set_size(150, 160);
    add_float(minimap, 190, 55);

    generate_map_preview();

    random_input.set_random(custom_mission.get_random_base());
    random_input.set_displayed(true);
    add_float(random_input, 19 + 31 * 8, 15);

    file_list.set_size(160, 160);
    file_list.set_displayed(false);
    file_list.set_selection_handler(method(self, function(_item) {
        /* Show the saved world in the preview pane, as picking a mission does. */
        var _loaded = game_store_load(_item);
        if (_loaded == undefined) {
            return;
        }
        map = _loaded.get_map();
        minimap.set_map(map);
        set_redraw();
    }));
    add_float(file_list, 20, 55);
}
